Updates on May 17, 2024 17:46
----------------------------------------------------------------------------------------
retroarch.mk 41db4b022a684292b9f4606775ed6ec1a3004127 # Version: Commits on May 17, 2024
----------------------------------------------------------------------------------------
vfs_implementation: Fix warning of unused `include_hidden` parameter (#16540)

This fixes a warning of the `include_hidden` parameter not being used outside of `_WIN32`.

```

vfs/vfs_implementation.c:1063:30: error: unused parameter â€˜include_hiddenâ€™ [-Werror=unused-parameter]

 1063 |       const char *name, bool include_hidden)

      |                              ^

cc1: all warnings being treated as error

```,

-------------------------------------------------------------------------------------------------------
libretro-beetle-pce-fast.mk 414149d335ce2a3284db6cdffbb8ed2ce42dbe5f # Version: Commits on May 17, 2024
-------------------------------------------------------------------------------------------------------
Fetch translations & Recreate libretro_core_options_intl.h,

--------------------------------------------------------------------------------------------------
libretro-beetle-psx.mk 1743ca1a97cc90eac463def2e6118602b3d230c0 # Version: Commits on May 17, 2024
--------------------------------------------------------------------------------------------------
Fetch translations & Recreate libretro_core_options_intl.h,

---------------------------------------------------------------------------------------------
libretro-bsnes.mk 37606e377ebae5d3175cd6267e4ddfa3f3c5091f # Version: Commits on May 17, 2024
---------------------------------------------------------------------------------------------
Fetch translations & Recreate libretro_core_options_intl.h,

------------------------------------------------------------------------------------------------
libretro-gambatte.mk 238b195bca073bc1a2032c4e92c097d157e521f8 # Version: Commits on May 17, 2024
------------------------------------------------------------------------------------------------
Fetch translations & Recreate libretro_core_options_intl.h,

-----------------------------------------------------------------------------------------------------
libretro-mame2003-plus.mk ad1eeb8b082a5eea1b8228b37aef68f375ec2f8b # Version: Commits on May 17, 2024
-----------------------------------------------------------------------------------------------------
COREDEFS never used. (#1727),

----------------------------------------------------------------------------------------------
libretro-mrboom.mk d9695504924344eb681b526d0cc3bb5e3884a32b # Version: Commits on May 17, 2024
----------------------------------------------------------------------------------------------
sdl2: remove trace,

---------------------------------------------------------------------------------------
amiberry.mk 540e9b85beda523cd8bc1675b3f67c8fe42c5f7c # Version: Commits on May 17, 2024
---------------------------------------------------------------------------------------
bugfix: Make guisan widgets active/inactive status more visible (fixes #1326)

Some widgets were not greyed out when disabled,

------------------------------------------------------------------------------------
pcsx2.mk 31e935d831c72f3e7a473e1cdbc807ad10656a79 # Version: Commits on May 17, 2024
------------------------------------------------------------------------------------
GzippedFileReader: Don't clamp chunkID on read,

---------------------------------------------------------------------------------------
alephone.mk fa992bf4bb8a47ec44d68d1df22ce0e449ec0c73 # Version: Commits on May 17, 2024
---------------------------------------------------------------------------------------
Fix rare case where physics (and other files) being messed up in M1,

------------------------------------------------------------------------------------
box64.mk 71c0aff78ff24e4ae10a1ac82921c7cd1d24d6f6 # Version: Commits on May 17, 2024
------------------------------------------------------------------------------------
Added 2 wrapped function libsdl2mixer ('two months' works now),

------------------------------------------------------------------------------------
cdogs.mk 470c9fc33400857f5f08f7ba22889fb65eb4f44a # Version: Commits on May 17, 2024
------------------------------------------------------------------------------------
Log walls #712,

---------------------------------------------------------------------------------------
fheroes2.mk d097964cb9af66ebf744eff25f0046a67853b1a3 # Version: Commits on May 17, 2024
---------------------------------------------------------------------------------------
Update translation files (#8668),

--------------------------------------------------------------------------------------
stalker.mk bc9f5894c8a0396a5b29eaad6a745785b34f0167 # Version: Commits on May 17, 2024
--------------------------------------------------------------------------------------
Layers/xrRenderPC_GL/gl_rendertarget_build_textures.cpp: removed FreeBSD crash workaround (#1223)

After e47e4fe057c4f3c7a56266c4666107c5b8edc4e1 the problem origin was removed, so we no longer need a workaround.,

----------------------------------------------------------------------------------
stk.mk fcd8cea5cd15fd59d09a26dcde137fb38f2bc6fb # Version: Commits on May 17, 2024
----------------------------------------------------------------------------------
Remove hardcoded 1 pixel,

------------------------------------------------------------------------------------
box86.mk 79e622a839f8002b066066164154e6c6e029ed41 # Version: Commits on May 17, 2024
------------------------------------------------------------------------------------
Setup stack nicely for pthread_once (might help wine),

----------------------------------------------------------------------------------------
doomretro.mk 88bc9b63dfd77636d1857dd48b960ebd9fc004af # Version: Commits on May 17, 2024
----------------------------------------------------------------------------------------
Minor tweaks,

----------------------------------------------------------------------------------------
sonic2013.mk 8def752b2f73226e201ae320b7905e03c6d34822 # Version: Commits on May 17, 2024
----------------------------------------------------------------------------------------
idk why you need this specific version in the first place [skip ci],

--------------------------------------------------------------------------------------
soniccd.mk 3691b65956f55383a31c40eed1152c1c83f8cc58 # Version: Commits on May 17, 2024
--------------------------------------------------------------------------------------
[skip ci],