package/nfs-utils: fix unmet direct dependency
Commit 062401516623670860b5383d4a5d76498796b7bb adds rpcbind as a dependency
without properly caring for the thread dependency.

rpcbind adds libtirpc as a dependendency which fails:
  fatal error: pthread.h: No such file or directory

Since we probably don't care much about using nfs-utils in a non-threaded
scenario, we simply disable nfs-utils for toolchains without thread support.

Fixes:
http://autobuild.buildroot.net/results/803/80321de8d4c6c0a00439b07289a5818962128b43/

Suggested-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>