package/trinity: needs headers >= 3.4
IPV6_UNICAST_IF was added with kernel 3.4:
https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/log/include/linux/in6.h?id=refs/tags/v3.4.112

To prove this compare with kernel 3.3:
https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/log/include/linux/in6.h?h=linux-3.3.y

The trinity package contains some compat code in
https://github.com/kernelslacker/trinity/blob/master/include/compat.h

but it does not trigger for IPV6_UNICAST_IF
https://github.com/kernelslacker/trinity/blob/master/include/compat.h#L662

Instead of hacking compat.h to death just depend on headers >= 3.4.

Fixes a build error
net/proto-ipv6.c: At top level:
net/proto-ipv6.c:157:12: error: ‘IPV6_UNICAST_IF’ undeclared here (not in a function)
  { .name = IPV6_UNICAST_IF, },

not yet caught by autobuilders using this defconfig:
http://autobuild.buildroot.net/results/394/394e22be0ef986463e97b3040dad8f978262732c/

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>