libsigc: bump to 2.2.10 to fix build with gcc 4.6
The build of libsigc 2.2.8 fails with gcc 4.6 with the following error
message:

In file included from signal_base.cc:20:0:
../sigc++/signal_base.h:48:11: error: 'size_t' does not name a type In file included from ../sigc++/signal.h:8:0,

The 2.2.9 version was released with a fix for this build problem, so
we directly bump to the latest version 2.2.10, which builds fine under
gcc 4.6.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>