Updates on Aug 30, 2025 22:28
---------------------------------------------------------------------------------------
amiberry.mk 26bec2a822857643209a57505facb77765f89551 # Version: Commits on Aug 30, 2025
---------------------------------------------------------------------------------------
enhancement: Added CD Drive controller support (fixes #1690)

Enabled option to add SCSI/IDE CD Drive. This doesn't (yet) support physical drives, or at least it hasn't been tested with such. It's been tested with CD images, and it allows the selection of controller and unit that the drive will appear under emulation.,

-----------------------------------------------------------------------------------
ares.mk be570117bb5bef271fc24c18ce6d9bb12ccbf689 # Version: Commits on Aug 30, 2025
-----------------------------------------------------------------------------------
CI: overwrite built-in pinned CMake installation,

-----------------------------------------------------------------------------------
cemu.mk 9267e72ef92fb30af35cc0e6c9b2afbc3dd703c7 # Version: Commits on Aug 30, 2025
-----------------------------------------------------------------------------------
refactor: Fix pugixml deprecation warnings (#1677),

----------------------------------------------------------------------------------
clk.mk 4639e1c47c2561cedeb18599c9399019449b0e04 # Version: Commits on Aug 30, 2025
----------------------------------------------------------------------------------
Merge pull request #1544 from TomHarte/Macros

Further reduce historical dependence on macros.,

------------------------------------------------------------------------------------------
duckstation.mk c1bb183caad3e89cc6b09319a67b0ae7b563e29e # Version: Commits on Aug 30, 2025
------------------------------------------------------------------------------------------
FullscreenUI: Fix selecting disc set entries in list/grid,

-------------------------------------------------------------------------------------
ppsspp.mk 43ffbffc4106e121f6b339830a8de23f98c20c8b # Version: Commits on Aug 30, 2025
-------------------------------------------------------------------------------------
Merge pull request #20769 from lvonasek/master

OpenXR - Support for Play for Dream MR headset,

--------------------------------------------------------------------------------------
shadps4.mk ed3f9ee62640de3c3caaf3bab66c82a8371ab067 # Version: Commits on Aug 30, 2025
--------------------------------------------------------------------------------------
Fix error compiling with certain math functions in std namespace (#3383)

e.g. error: no member named 'atan2f' in namespace 'std',

---------------------------------------------------------------------------------------
thextech.mk 143c770b21ee93888a013687e2edc58ef10b7691 # Version: Commits on Aug 30, 2025
---------------------------------------------------------------------------------------
Translated using Weblate (Japanese)

Currently translated at 70.5% (12 of 17 strings)

Translated using Weblate (Japanese)

Currently translated at 1.7% (7 of 393 strings)

Co-authored-by: 3UPPER <mail.3UPPER@gmail.com>

Translate-URL: https://hosted.weblate.org/projects/thextech/android-launcher-arrays/ja/

Translate-URL: https://hosted.weblate.org/projects/thextech/engine-assets-specific/ja/

Translation: TheXTech Engine/Android launcher (arrays)

Translation: TheXTech Engine/Engine Assets-specific,

-----------------------------------------------------------------------------------
ymir.mk 3ed69dcaecbe6104d9190db4e671f039b8cebd10 # Version: Commits on Aug 30, 2025
-----------------------------------------------------------------------------------
perf(VDP2): Precompute per-dot rotation coefficient flag instead of deriving it twice per scanline,

------------------------------------------------------------------------------------
box64.mk 197f962543814edd6c115878ae353aed1d2dad9f # Version: Commits on Aug 30, 2025
------------------------------------------------------------------------------------
[WRAPPER] Wrapped 2 more symbols for libfreetype (#2984),

---------------------------------------------------------------------------------------
corsixth.mk a44192a4878c37da4df9cc12fcc63f3c9dab3ba2 # Version: Commits on Aug 30, 2025
---------------------------------------------------------------------------------------
Merge pull request #2988 from lewri/improve_staff_leaving_room

Don't allow patient entry if staff want rest,

----------------------------------------------------------------------------------------
retroarch.mk 3ebc2f7db2d9298397b1dc711d69fbb99f44c6b3 # Version: Commits on Aug 30, 2025
----------------------------------------------------------------------------------------
Also ignore initial mouse position after refresh rate change,

-------------------------------------------------------------------------------------
gzdoom.mk 3d39bf33bb1f94af8dc88bee5d4dbcc712687d0b # Version: Commits on Aug 29, 2025
-------------------------------------------------------------------------------------
Re-add handler param to MessageBox Init virtual

This is just to prevent breaking any existing overrides. The value is fully unused.,

-----------------------------------------------------------------------------------
tr1x.mk 13b3e55c30ab4bc923b0a2b2f3950fc065230313 # Version: Commits on Aug 30, 2025
-----------------------------------------------------------------------------------
docs/tr2: release 1.4.1,

-----------------------------------------------------------------------------------
tr2x.mk 13b3e55c30ab4bc923b0a2b2f3950fc065230313 # Version: Commits on Aug 30, 2025
-----------------------------------------------------------------------------------
docs/tr2: release 1.4.1,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk 42b0a9a13d414dd5b3250d3ea06799eb707d0728 # Version: Commits on Aug 30, 2025
------------------------------------------------------------------------------------------
scripts: gha: copy SDL library with all symlinks to it,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk 43ffbffc4106e121f6b339830a8de23f98c20c8b # Version: Commits on Aug 30, 2025
----------------------------------------------------------------------------------------------
Merge pull request #20769 from lvonasek/master

OpenXR - Support for Play for Dream MR headset,

------------------------------------------------------------------------------------------------
libretro-theodore.mk 242e932d838284a61b81aa7641c60d813934025e # Version: Commits on Aug 30, 2025
------------------------------------------------------------------------------------------------
Use newer psp dev kit,

---------------------------------------------------------------------------------------------
libretro-vba-m.mk 043956753b44c58f1c5a08cab40570adebce3bac # Version: Commits on Aug 30, 2025
---------------------------------------------------------------------------------------------
translations: transifex pull

Signed-off-by: Rafael Kitover <rkitover@gmail.com>,