configs/beaglebone: Bump U-Boot version
Currently selected version of U-Boot fails to compile.
Dying words are:

  gcc -g -O2 -I/home/zeta/buildroot/buildroot/output/host/usr/include -c -o env_embedded.o /home/zeta/buildroot/buildroot/output/build/uboot-2013.10/common/env_embedded.c
  /home/zeta/buildroot/buildroot/output/build/uboot-2013.10/lib/crc32.c:14:20: fatal error: common.h: No such file or directory
  compilation terminated.
  Makefile:258: recipe for target 'crc32.o' failed

Since it's quite old, instead of trying to fix it, let's
just upgrade.

Signed-off-by: Ezequiel Garcia <ezequiel@vanguardiasur.com.ar>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>