xapp_xsm: depends on MMU
Fixes: http://sysmic.org/~jezz/results/455f2788:

remote.o: In function `_remote_start':
remote.c:(.text+0x74): undefined reference to `_fork'
restart.o: In function `_Clone':
restart.c:(.text+0x5a8): undefined reference to `_fork'
restart.o: In function `_Restart':
restart.c:(.text+0xa44): undefined reference to `_fork'
collect2: ld returned 1 exit status

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>