uclibc: backport upstream patch adding fcntl definitions on OpenRISC
A number of fcntl.h definitions were missing on OpenRISC in uClibc-ng,
causing build failures such as:

gfile.c: In function 'splice_stream_with_progress':
gfile.c:3017:35: error: 'F_SETPIPE_SZ' undeclared (first use in this function)
   buffer_size = fcntl (buffer[1], F_SETPIPE_SZ, 1024 * 1024);

This comit backports a patch that was merged in upstream uClibc-ng,
which addresses this problem.

Fixes:

  http://autobuild.buildroot.net/results/182ebbba6c7466b07e965e5120d919cbcf5e9da6/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>