gstreamer1: fix compile for microblaze and xtensa architectures
Fix unaligned access support detection introduced to gstreamer
by commit 'gstconfig.h: Detect unaligned access support at compile-time' ([1])
by assuming no unaligned support for unknown architectures.

Fixes [2], [3]:

  ../gst/gstconfig.h:112:4: error: #error "Could not detect architecture; don't know whether it supports unaligned access! Please file a bug."
  #  error "Could not detect architecture; don't know whether it supports unaligned access! Please file a bug."

[1] https://cgit.freedesktop.org/gstreamer/gstreamer/commit/?h=1.10&id=6ef601367e0f5adb7a8b02cec94dec04fccf701a
[2] http://autobuild.buildroot.net/results/c1cd60d3f44f2938e5f42453d034ea070898f837
[3] http://autobuild.buildroot.net/results/c3a6662f0acfda179a58cdad9165f36826229826

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>