Updates on Nov 25, 2024 16:00
-----------------------------------------------------------------------------------------------------
chromebook-linux-audio.mk e171791e615cb52b808b2b4108ce7ac71298a827 # Version: Commits on Nov 25, 2024
-----------------------------------------------------------------------------------------------------
switch to alsa-ucm-conf-cros ucm repo,

-------------------------------------------------------------
chromebook-ucm-conf.mk 0.7 # Version: Commits on Nov 25, 2024
-------------------------------------------------------------
-

---------------------------------------------------------------------------------------
amiberry.mk d3448bebdaecdc7a47b9f9fd0cc586da95d36cea # Version: Commits on Nov 25, 2024
---------------------------------------------------------------------------------------
refactor: minor line cleanup,

------------------------------------------------------------------------------------
citra.mk b970c857f982b74d80e87a6065c1f61d0b23437c # Version: Commits on Nov 25, 2024
------------------------------------------------------------------------------------
Android: Implement `Use Virtual SD Card` setting (#269),

------------------------------------------------------------------------------------------
dolphin-emu.mk cd0b13603d2e73940be7b357c26949dc77aed2dc # Version: Commits on Nov 25, 2024
------------------------------------------------------------------------------------------
Merge pull request #13191 from dreamsyntax/sdl-patch

Externals: Update SDL to 2.30.9,

------------------------------------------------------------------------------------------
duckstation.mk 57595c47af8139d6e2b8459d65b24230abc263f5 # Version: Commits on Nov 25, 2024
------------------------------------------------------------------------------------------
GPU/TextureCache: Move replacement cache onto the GPU

And enforce a maximum. Should sort out the upload spam.,

-------------------------------------------------------------------------------------
hatari.mk 8a09f2326b2bd4808757cca2b1022258d565687e # Version: Commits on Nov 24, 2024
-------------------------------------------------------------------------------------
Add --scsi-ver command line option

To override the already existing config file option for SCSI version.

Add a helper function for <drive>=<value> option argument parsing, as

that was already done in 3 different places, and this adds one more.,

---------------------------------------------------
pcsx2.mk v2.3.28 # Version: Commits on Nov 25, 2024
---------------------------------------------------
- [CDVD: Fix OSDSYS Audio CD regressions.](https://github.com/PCSX2/pcsx2/pull/12032)

-------------------------------------------------------------------------------------
ppsspp.mk fe38e8822c350287444f5da050e42b8c7ff6b804 # Version: Commits on Nov 24, 2024
-------------------------------------------------------------------------------------
Merge pull request #19654 from hrydgard/additional-imdebugger-features

ImDebugger: Add Breakpoints window,

---------------------------------------------------------------
ruffle.mk nightly-2024-11-25 # Version: Commits on Nov 25, 2024
---------------------------------------------------------------
## What's Changed

* frontend_utils: Make Ruffle Bundle errors more verbose by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/18727

* text: Fix rounding in TextFormat by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/18701

* Revert \wgpu: Perform blends as-needed, instead of ahead of time. Reduces memory usage for multiple blends significantly\ by @adrian17 in https://github.com/ruffle-rs/ruffle/pull/18742

* avm2: Refactor TObject call and construct by @Lord-McSweeney in https://github.com/ruffle-rs/ruffle/pull/18696

* audio: Add AAC decoding by @torokati44 in https://github.com/ruffle-rs/ruffle/pull/16526

* text: Fix calculation of text size by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/18708

* text: Remove EditText::line_width by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/18748

**Full Changelog**: https://github.com/ruffle-rs/ruffle/compare/nightly-2024-11-24...nightly-2024-11-25,

--------------------------------------------------------------------------------------
scummvm.mk 2f5633d3a94b5075f089c74566017ea8f44e0901 # Version: Commits on Nov 25, 2024
--------------------------------------------------------------------------------------
I18N: Update translation files

Updated by \Update PO files to match POT (msgmerge)\ hook in Weblate.

Translation: ScummVM/scummvm

Translate-URL: https://translations.scummvm.org/projects/scummvm/scummvm/,

--------------------------------------------------------------------------------------
shadps4.mk 2226175d9bea600028facc9c8cefb75a1ebe79ec # Version: Commits on Nov 25, 2024
--------------------------------------------------------------------------------------
Fix Shortcut (#1586),

---------------------------------------------------------------------------------------
thextech.mk 9b35b8637d98d37c15dcb307851bd22dedfc82da # Version: Commits on Nov 25, 2024
---------------------------------------------------------------------------------------
CI: Bump artifacts uploader to v4

Otherwise, v3 is deprecated,

-------------------------------------------------
vice.mk r45377 # Version: Commits on Nov 25, 2024
-------------------------------------------------
added support for 'BMP Data Turbo 2000' cartridge

git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@45377 379a1393-f5fb-40a0-bcee-ef074d9b53f7,

-------------------------------------------------------------------------------------------
xenia-canary.mk 2300b8455c1ff3ef71a3f95715f09b95cad83bc6 # Version: Commits on Oct 27, 2024
-------------------------------------------------------------------------------------------
[Tools] Updating: vswhere.exe and premake5.exe,

------------------------------------------------------------------------------------
box64.mk a71856801b2a9f36a8745d0285778e6654a3408d # Version: Commits on Nov 25, 2024
------------------------------------------------------------------------------------
[WRAPPERHELPER] Added the `--gst` option (#2072),

------------------------------------------------------------------------------------------
devilutionx.mk 36e0abfc35d12ee57354a6ebca434ec78e3e7e90 # Version: Commits on Nov 24, 2024
------------------------------------------------------------------------------------------
Fix -Wunused-const-variable in controller_buttons,

------------------------------------------------------------------------------------------
dxx-rebirth.mk ebe4aceb721894ff614481e97c50df0fd7e3e814 # Version: Commits on Nov 16, 2024
------------------------------------------------------------------------------------------
valptridx: fix ambiguous overload resolution

gcc-15 and clang-18 both reject the previous code.  gcc-12, gcc-13, and

gcc-14 accept the previous code.  gcc-14 produces the same program with

both the old and new code, so this is not a behavior change.

gcc-15 rejects the old code with:

```

In file included from similar/main/aipath.cpp:51:

similar/main/aipath.cpp: In function 'void d2x::{anonymous}::ai_path_garbage_collect()':

similar/main/aipath.cpp:1367:35: error: ambiguous overload for 'operator*' (operand type is 'valptridx<d2x::object>::basic_vval_member_factory<valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc>, valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vm> >::iterator<valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc> >' {aka 'valptridx<d2x::object>::factory_range_iterator<valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc> >'})

 1367 |     range_for (const auto &&objp, vcobjptridx)

      |                                   ^~~~~~~~~~~

common/include/compiler-range_for.h:9:31: note: in definition of macro 'range_for'

    9 | #define range_for(A,B)  for(A:B)

      |                               ^

similar/main/aipath.cpp:1367:35: note: candidate: 'operator*(valptridx<d2x::object>::ptr<valptridx<d2x::object>::vc>::const_pointer_type {aka const d2x::object*})' (built-in)

 1367 |     range_for (const auto &&objp, vcobjptridx)

      |                                   ^~~~~~~~~~~

common/include/compiler-range_for.h:9:31: note: in definition of macro 'range_for'

    9 | #define range_for(A,B)  for(A:B)

      |                               ^

similar/main/aipath.cpp:1367:35: note: candidate: 'operator*(valptridx<d2x::object>::ptr<valptridx<d2x::object>::vc>::mutable_pointer_type {aka d2x::object*})' (built-in)

 1367 |     range_for (const auto &&objp, vcobjptridx)

      |                                   ^~~~~~~~~~~

common/include/compiler-range_for.h:9:31: note: in definition of macro 'range_for'

    9 | #define range_for(A,B)  for(A:B)

      |                               ^

In file included from common/main/object.h:40,

                 from similar/main/aipath.cpp:36:

common/include/valptridx.h:672:15: note: candidate: 'typename policy::reference valptridx<managed_type>::ptr<policy>::operator*() const & [with policy = valptridx<d2x::object>::vc; managed_type = d2x::object; typename policy::reference = const d2x::object&]'

  672 |     reference operator*() const &

      |               ^~~~~~~~

common/include/valptridx.h:1229:16: note: candidate: 'valptridx<managed_type>::factory_range_iterator<T>::value_type valptridx<managed_type>::factory_range_iterator<T>::operator*() const & requires !(is_same_v<typename std::conditional<requires{typename T::vidx_type;}, T, managed_type>::type, managed_type>) [with T = valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc>; managed_type = d2x::object; value_type = valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc>]'

 1229 |     value_type operator*() const &

      |                ^~~~~~~~

```

Reported-by: koo5 <https://github.com/dxx-rebirth/dxx-rebirth/issues/803> (clang-18 only),

-------------------------------------------------------------------------------------------
jazz2-native.mk 75782006494691ca413ab3a44bf3f3e0a323b85f # Version: Commits on Nov 25, 2024
-------------------------------------------------------------------------------------------
Removed debug code,

---------------------------------------------------------------------------------------------
theforceengine.mk 297918d2c28e79f8844d98654ab10fefa643180c # Version: Commits on Nov 25, 2024
---------------------------------------------------------------------------------------------
Subdirectory related amendments (#474)

* Add ExternalData directory to CMakeLists.txt

* Move external data files to game-based subdirectory,

-----------------------------------------------------------------------------------
re2c.mk e5cb9a1ebd9efab6604930b9f773fd684df6edd5 # Version: Commits on Nov 25, 2024
-----------------------------------------------------------------------------------
Release 4.0.1.,

------------------------------------------------------------
syncthing.mk v1.28.1-rc.2 # Version: Commits on Nov 25, 2024
------------------------------------------------------------
Bugfixes:

- #9400: Folder overlap not detected when using tilde

- #9590: WebUI table column widths broken on iPhone 12 Pro Max and wider

- #9686: Sync status stays at 'Syncing xx%\ when remote device pauses the folder.

- #9757: Firefox, dark theme: device ID is hard to read

- #9775: Junctions as dirs doesn't work anymore

- #9776: Disabled checkbox panels don't respect dark theme

- #9783: gui: Address override not respected in fresh default config

- #9821: panic: runtime error: index out of range [-1]

Enhancements:

- #9725: Ignoring symbolic links when syncing on android as well

,

----------------------------------------------------------------------------------------
new-lg4ff.mk 6100a34c182536c607af80e119d54a66c6fb2a23 # Version: Commits on Nov 18, 2024
----------------------------------------------------------------------------------------
Fix build on Linux 6.12,

----------------------------------------------------------------------------------------
retroarch.mk b2af02f9fb34c8e32c67f5948957b9045c01258e # Version: Commits on Nov 25, 2024
----------------------------------------------------------------------------------------
apple: include mrboom core in App Store builds (#17207),

-------------------------------------------------------------------------------------
gzdoom.mk 5576e66670c98989851acb319c7e3c8ae4948534 # Version: Commits on Nov 24, 2024
-------------------------------------------------------------------------------------
make if-checks for AppendStatusBar consistent with Zandronum implementation,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk 6b24b263ab61fb717ac6254611cce50ea21999ed # Version: Commits on Nov 24, 2024
------------------------------------------------------------------------------------------
engine: host: expose new -clientport settings. Realign options,

---------------------------------------------------------------------------------------------
libretro-fbneo.mk b581eda6c7f195ff86d1c3bc6d721f142870bae4 # Version: Commits on Nov 25, 2024
---------------------------------------------------------------------------------------------
(libretro) update files,

--------------------------------------------------------------------------------------------
libretro-mgba.mk 7ec56763f9d6c68f8d3f7f16a9e34fffcd765492 # Version: Commits on Nov 25, 2024
--------------------------------------------------------------------------------------------
Qt: Fix installer updates if a version number is in the filename (fixes #3109),

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk fe38e8822c350287444f5da050e42b8c7ff6b804 # Version: Commits on Nov 24, 2024
----------------------------------------------------------------------------------------------
Merge pull request #19654 from hrydgard/additional-imdebugger-features

ImDebugger: Add Breakpoints window,

-----------------------------------------------------------------------------------------------
libretro-scummvm.mk 2f5633d3a94b5075f089c74566017ea8f44e0901 # Version: Commits on Nov 25, 2024
-----------------------------------------------------------------------------------------------
I18N: Update translation files

Updated by \Update PO files to match POT (msgmerge)\ hook in Weblate.

Translation: ScummVM/scummvm

Translate-URL: https://translations.scummvm.org/projects/scummvm/scummvm/,

---------------------------------------------------------------------------------------------
libretro-vba-m.mk c85397518b601e1be832f566aa2c740bf75147b9 # Version: Commits on Nov 25, 2024
---------------------------------------------------------------------------------------------
[win32-deps] Update win32-deps (#1375),