e2fsprogs: fix musl compile (__GNUC_PREREQ related)
Add void-linux provided patch to use __GNUC_PREREQ macro only
in case it is defined (patch taken from [1]).

Fixes [2]:

  In file included from ../../lib/ext2fs/ext2fs.h:97:0,
                   from feature.c:20:
  ../../lib/ext2fs/hashmap.h:20:19: error: missing binary operator before token "("
   #if __GNUC_PREREQ (4, 8)
                     ^
  ../../lib/ext2fs/hashmap.h:25:19: error: missing binary operator before token "("
   #if __GNUC_PREREQ (4, 8)
                     ^

Problem already upstream reported by Baruch Siach (see [3]).

[1] https://raw.githubusercontent.com/void-linux/void-packages/1f3b51493031cc0309009804475e3db572fc89ad/srcpkgs/e2fsprogs/patches/fix-glibcism.patch
[2] http://autobuild.buildroot.net/results/e49d9333086ed714fa193b79b49c53e9cc511fec
[3] https://www.spinics.net/lists/linux-ext4/msg62290.html

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>