gst1-validate: disable building documentation using sphinx
Fix a build failure in case (a non functional) sphinx documentation
system is installed on the host (reported [1] and fix tested [2]
by grunpferd@netscape.net).

Fixes:

  sphinx-build -b html -d ./doctrees   . ./html
  Error: Source directory doesn't contain a conf.py file.

[1] http://lists.busybox.net/pipermail/buildroot/2017-August/200021.html
[2] http://lists.busybox.net/pipermail/buildroot/2017-August/200267.html

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Cc: grunpferd@netscape.net
[Arnout:
 - use --disable-sphinx-doc instead of a cv variable
 - remove the comment, it speaks for itself]
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>