package/upx: fix build with host gcc 6.x
Disable the -Werror gcc option because is causes the following error
when using gcc 6.x on the host.

 p_vmlinx.cpp:100:5: error: this ‘if’ clause does not guard...
  [-Werror=misleading-indentation] if (a->p_paddr > b->p_paddr) return  1;

Signed-off-by: Martin Bark <martin@barkynet.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>