Updates on Feb 07, 2026 20:43
Updates on Feb 07, 2026 20:43
-----------------------------------------------------------------------------------------------
dolphin-triforce.mk fe0b688e5083a3ced9c2f905e7f119034aed4588 # Version: Commits on Feb 07, 2026
-----------------------------------------------------------------------------------------------
Android: Add Triforce Baseboard

This lets users select Triforce Baseboard for SI and SP1. Limitations:

* The test, service and coin buttons can be bound to gamepads and other

  physical inputs, but aren't available in the touch input overlay.

* The IP overrides are exposed to the user as a raw string rather than

  a table like in DolphinQt.,

-------------------------------------------------------------------------------------
hatari.mk 4d0bf09a245f21ebdec0ef5f1867000ec8449e9b # Version: Commits on Feb 07, 2026
-------------------------------------------------------------------------------------
Allow to configure the SDL audio buffer size with SDL3, too,

--------------------------------------------------------------------------------------
openmsx.mk e7f600e17b48d2f7e3e22a4f23acee91e8913c63 # Version: Commits on Feb 07, 2026
--------------------------------------------------------------------------------------
Make spelling of MSX Music more consistent.,

---------------------------------------------------
pcsx2.mk v2.7.99 # Version: Commits on Feb 07, 2026
---------------------------------------------------
- [Qt: Update copyright year in AsyncDialogs.cpp and AsyncDialogs.h](https://github.com/PCSX2/pcsx2/pull/13966)

,

-------------------------------------------------------------------------------------
ppsspp.mk 1ce9db0250501ff30219fe4255bdbf96c7043904 # Version: Commits on Feb 07, 2026
-------------------------------------------------------------------------------------
Merge pull request #21217 from hrydgard/more-ui-changes

Fix 32-bit windows build, minor UI fixes,

------------------------------------------------------
shadps4.mk v.0.14.0 # Version: Commits on Feb 07, 2026
------------------------------------------------------
tagged 0.14.0,

-----------------------------------------------------------------------------------------
supermodel.mk fe00551bbffc60242a6429494a7bb4ed568d1b81 # Version: Commits on Feb 07, 2026
-----------------------------------------------------------------------------------------
Merge pull request #302 from ToBul/master

[README.txt] LA Machines calibration, Ski Champ camera view info,

--------------------------------------------------------------------------------------
tsugaru.mk 4447eb32b2616d02a7ed025ca3db5cc8f3ce9e20 # Version: Commits on Feb 07, 2026
--------------------------------------------------------------------------------------
Removed PAUSE from pull-down menu.  Actually, this menu was visible only when the VM is already paused, and was not doing anything.,

-------------------------------------------------------------------------------------------
xenia-canary.mk 1a9613705db68df47ce13fa469abb032c182f247 # Version: Commits on Feb 06, 2026
-------------------------------------------------------------------------------------------
Rework max anisotropy override to sampler creation (D3D12/Vulkan)

Revert ac6fd65 fetch additions and implement context-sensitive AF override.,

-------------------------------------------------------------------------------------------
xenia-native.mk 1a9613705db68df47ce13fa469abb032c182f247 # Version: Commits on Feb 06, 2026
-------------------------------------------------------------------------------------------
Rework max anisotropy override to sampler creation (D3D12/Vulkan)

Revert ac6fd65 fetch additions and implement context-sensitive AF override.,

-------------------------------------------------------------------------------------
ikemen.mk e3eb3718540dda490ff141de1b0e3b2f93d0f8bb # Version: Commits on Feb 07, 2026
-------------------------------------------------------------------------------------
style: fix code style issues with gofmt,

---------------------------------------------------------------------------------------
thextech.mk 2691bf78275d15cb436ff3dc9c28cf9a2c89f953 # Version: Commits on Feb 07, 2026
---------------------------------------------------------------------------------------
player.cpp: add some effects to Cyclone (#1103),

------------------------------------------------------------------------------------
tic80.mk 8f7f36d2db99748bef8c65ee48657937ce4764cc # Version: Commits on Feb 07, 2026
------------------------------------------------------------------------------------
Update vendor/zip from v0.1.19 to v0.3.6 (#2883)

* Updates verdor/zip from v0.1.19 to v0.3.5

no need for the -DCMAKE_POLICY_VERSION_MINIMUM=3.5 flag anymore.

* uses zip v0.2.6 instead of v.3.5

due to:

zip/src/miniz.h:8503:30: error: comparison is always false due to

limited range of data type [-Werror=type-limits]

8503 |     if (((mz_uint64)buf_size > 0xFFFFFFFF) || (uncomp_size >

0xFFFFFFFF)) {

* tries zip v0.3.5 again

but with the -Wno-type-limits flag

* Update vendor/zip to 0.3.6

* Add -Wno-stringop-truncation to zip compile options

* Refactor compiler option checks for zip to only apply -Wno-stringop-truncation for GCC

* Fix for  Baremetal GCC treating string truncation warnings as errors

* Fix support for bare-metal environment by defining lstat as stat

* Format comment

---------

Co-authored-by: imsys <911254+imsys@users.noreply.github.com>,

------------------------------------------------------------------------------------
box64.mk 322a9f17c52191212d6377fe50e1c02a19d6c045 # Version: Commits on Feb 07, 2026
------------------------------------------------------------------------------------
[WRAPPER][VULKAN] Added hard-coded white list for x64 vulkan overlay,

-----------------------------------------------------------------------------------------
catacombgl.mk 50f77c0b3977389033d259eb4ce97fb0af2d776a # Version: Commits on Feb 07, 2026
-----------------------------------------------------------------------------------------
Enable class test for loading Catacomb Abyss v1.12 DOS saved game,

---------------------------------------------------------------------------------------
etlegacy.mk 4974a05ee200cc5cd3d396fce07e477a2ea4ceb7 # Version: Commits on Feb 07, 2026
---------------------------------------------------------------------------------------
ui: add shoutcaster score cmd in control menu,

-------------------------------------------------------------------------------------------
jazz2-native.mk cb5d3e01fdb2a36ad392d5869b54055263feee37 # Version: Commits on Feb 07, 2026
-------------------------------------------------------------------------------------------
Updated Russian Translation (#126)

Changed some errors and added new translations. Now the translation is 100%,

----------------------------------------------------------------------------------------
supertux2.mk d4088484159ab92c32b136d4191195e469d9f10c # Version: Commits on Feb 07, 2026
----------------------------------------------------------------------------------------
root_sapling: spawn a bit below when spawning in slopes

This is so that the root isn't exposed when spawning in slopes.

closes #3607,

----------------------------------------------------------------
wine-mono.mk wine-mono-11.0.0 # Version: Commits on Feb 07, 2026
----------------------------------------------------------------
Release 11.0.0.,

---------------------------------------------------------------------------------------------
easyrpg-player.mk 21c8985152ff0d8e3e6cbc7c0d0f930c81838109 # Version: Commits on Feb 07, 2026
---------------------------------------------------------------------------------------------
Merge pull request #3517 from carstene1ns/update/flat-meta

Upate metainfo and flatpak manifest,

----------------------------------------------------------------------------------------
doomretro.mk 137c23408ad7720726a87d1673d90e448d9c7353 # Version: Commits on Feb 07, 2026
----------------------------------------------------------------------------------------
Apply teleport zoom when using `teleport` CCMD,

--------------------------------------------------------------------------------------
yquake2.mk bf74112ade2c7e90993bc7e3ada6d79f448bcd6c # Version: Commits on Feb 07, 2026
--------------------------------------------------------------------------------------
game: cleanup heretic 2 object definitions,

----------------------------------------------------------------------------------
trx.mk f8385f2c94d185a2b358a242d9bc0ec1f3660181 # Version: Commits on Feb 06, 2026
----------------------------------------------------------------------------------
lara/skin: absorb back gun object,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk 1c1e5c50a9d824a770aa22a3f3b49490a491de45 # Version: Commits on Feb 07, 2026
------------------------------------------------------------------------------------------
3rdparty: mainui: update,

---------------------------------------------------------------------------------------------
libretro-citra.mk 2bc6a3e6d7ed4e3cf9e73caaeb3314c3c680b687 # Version: Commits on Feb 05, 2026
---------------------------------------------------------------------------------------------
libretro: microphone support,

-----------------------------------------------------------------------------------------------
libretro-easyrpg.mk 21c8985152ff0d8e3e6cbc7c0d0f930c81838109 # Version: Commits on Feb 07, 2026
-----------------------------------------------------------------------------------------------
Merge pull request #3517 from carstene1ns/update/flat-meta

Upate metainfo and flatpak manifest,

-------------------------------------------------------------------------------------------------
libretro-geargrafx.mk 915b3a1c285c37d1ddff38899dbb3960aad2cdb9 # Version: Commits on Feb 07, 2026
-------------------------------------------------------------------------------------------------
[debugger] Imrpove call stack window,

--------------------------------------------------------------------------------------------
libretro-pc98.mk 44c8a8c61640f2d5476af5224dbd88a36079f45d # Version: Commits on Feb 07, 2026
--------------------------------------------------------------------------------------------
fix SDL3 audio 2,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk 1ce9db0250501ff30219fe4255bdbf96c7043904 # Version: Commits on Feb 07, 2026
----------------------------------------------------------------------------------------------
Merge pull request #21217 from hrydgard/more-ui-changes

Fix 32-bit windows build, minor UI fixes,

---------------------------------------------------------------------------------------------
libretro-tic80.mk 8f7f36d2db99748bef8c65ee48657937ce4764cc # Version: Commits on Feb 07, 2026
---------------------------------------------------------------------------------------------
Update vendor/zip from v0.1.19 to v0.3.6 (#2883)

* Updates verdor/zip from v0.1.19 to v0.3.5

no need for the -DCMAKE_POLICY_VERSION_MINIMUM=3.5 flag anymore.

* uses zip v0.2.6 instead of v.3.5

due to:

zip/src/miniz.h:8503:30: error: comparison is always false due to

limited range of data type [-Werror=type-limits]

8503 |     if (((mz_uint64)buf_size > 0xFFFFFFFF) || (uncomp_size >

0xFFFFFFFF)) {

* tries zip v0.3.5 again

but with the -Wno-type-limits flag

* Update vendor/zip to 0.3.6

* Add -Wno-stringop-truncation to zip compile options

* Refactor compiler option checks for zip to only apply -Wno-stringop-truncation for GCC

* Fix for  Baremetal GCC treating string truncation warnings as errors

* Fix support for bare-metal environment by defining lstat as stat

* Format comment

---------

Co-authored-by: imsys <911254+imsys@users.noreply.github.com>,

---------------------------------------------------------------------------------------------
libretro-wasm4.mk 59107843a639c3fd17e15dfdf7bbe65360f3080e # Version: Commits on Feb 07, 2026
---------------------------------------------------------------------------------------------
feat: move website deployment from Netlify to GitHub Pages

Replace Netlify CI with GitHub Actions + Pages deployment for better

build visibility. The build-site job builds the website on all pushes

and PRs, while deploy-site only deploys to GitHub Pages on main branch

pushes.

Closes #810,