mpatrol: remove package
It doesn't compile:

../../src/memory.c: In function '__mp_memquery':
../../src/memory.c:769: error: lvalue required as left operand of assignment

And hasn't seen any updates since it got added in 2006, so it cannot
have many users. People most likely use valgrind nowadays for memory
debugging anyway - Drop it.

Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>