package/luaposix: add patch to fix musl compatibility
Backport patch from upstream to fix musl build error:

```
In file included from ext/posix/posix.c:25:0:
ext/posix/sched.c: In function 'Psched_setscheduler':
ext/posix/sched.c:74:9: error: variable 'sched_param' has initializer but incomplete type
  struct sched_param sched_param = {0};
```

Fixed upstream by commit 11cc8a2973569ec7fb1e7c2466dca0282944b124.

[Thomas: add missing <pkg>_AUTORECONF=YES.]

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>