Updates on Jan 05, 2025 17:59
---------------------------------------------------------------------------------------
amiberry.mk 87704643f87c262be965d66b22a99cbdab16b6e0 # Version: Commits on Jan 05, 2025
---------------------------------------------------------------------------------------
feat: Implement shortcut handling in disk_selection function (fixes #1559)

The `disk_selection` function in `amiberry_gui.cpp` has been updated to handle various types of shortcuts. The parameter name has been changed from `drive` to `shortcut`. The function now supports:

- Floppy disk images (shortcuts 0-3)

- Loading save states (shortcut 4)

- Saving save states (shortcut 5)

- Selecting CD images (shortcut 6),

-------------------------------------------------------------------------------------------
xenia-canary.mk d660a82997f24747b54e4ecea141c241d8336bcb # Version: Commits on Jan 05, 2025
-------------------------------------------------------------------------------------------
[XContent] Aggregate license mask from all licenses while installing package

This should fix issues with some DLCs,

----------------------------------------------------------------------------------------
rpi-utils.mk 02e3ffeee7dc8f954271fd42a3ed983567c55eb4 # Version: Commits on Jan 05, 2025
----------------------------------------------------------------------------------------
piolib: fixes may be used uninitialized

Fixes compile error:

    In function 'quadrature_encoder_get_count',

        inlined from 'main' at /build/bcm2835-utils/piolib/examples/quadrature_encoder.c:58:21:

/build/bcm2835-utils/piolib/examples/quadrature_encoder.pio.h:106:12: error: 'ret' may be used uninitialized [-Werror=maybe-uninitialized]

      106 |     return ret;

          |            ^~~,

------------------------------------------------------------------------------------
box64.mk b79ba11d95bdfdbcaa3edd636aec86a49c2113fc # Version: Commits on Jan 05, 2025
------------------------------------------------------------------------------------
[DYNAREC] Imroved log on signal and flags/sse info gathering. [ARM64_DYNAREC] Fixed some case of nat flags being incorectly used,

-------------------------------------------------------------------------------------------
jazz2-native.mk f2a5e0b9ccbd91145d8d8b13fe624cd0eca7660a # Version: Commits on Jan 05, 2025
-------------------------------------------------------------------------------------------
Refactoring,

--------------------------------------------------------------------------------------
stalker.mk de4b3fc61c47efb0300d6e7b5a82b5580e3f6bb1 # Version: Commits on Jan 02, 2025
--------------------------------------------------------------------------------------
xrUICore/SpinBox/UICustomSpin.cpp: compatibility with CS (#382),

-----------------------------------------------------------------------------------------
libpinmame.mk c98003f3096b0cda4749f93b0389456b38ccdee5 # Version: Commits on Jan 05, 2025
-----------------------------------------------------------------------------------------
Fix Elvis/Monopoly flipper, SAM cleanups, bug list update,

---------------------------------------------------------------------------------------
vpinball.mk d6a20659c69fe27f4059a8b2db36135647bdd868 # Version: Commits on Jul 23, 2024
---------------------------------------------------------------------------------------
misc: standalone builds for macos, ios, tvos, android, linux, and rpi,

---------------------------------------------------------------------------------------------
libretro-cap32.mk f8f4b0b704c44970001fcf839d8d010e5af435ff # Version: Commits on Jan 05, 2025
---------------------------------------------------------------------------------------------
[RMP] new homebrew added and classic mastertronic darts game!,

--------------------------------------------------------------------------------------------------
libretro-gearsystem.mk e0763fbbfd09f48a4aa007eb98e7363b2746f12d # Version: Commits on Jan 05, 2025
--------------------------------------------------------------------------------------------------
Add 4 Pak All Action mapper. Fix #115,

------------------------------------------------------------------------------------------------
libretro-nestopia.mk 9762adc00668f3a2e1016f3ad07ff9cbf9d67459 # Version: Commits on Jan 05, 2025
------------------------------------------------------------------------------------------------
NstDatabase: Kid Icarus (USA, Europe) (Rev 1) now defaults to NTSC region,