dhcpcd: fix ipv6 related compile failure
Add '-D_GNU_SOURCE' to gain missing struct in6_pktinfo definition.

Fixes [1]:

ipv6.h:211:41: error: invalid application of 'sizeof' to incomplete type 'struct in6_pktinfo'
  unsigned char sndbuf[CMSG_SPACE(sizeof(struct in6_pktinfo))];
                                         ^
ipv6.h:195:38: error: invalid application of 'sizeof' to incomplete type 'struct in6_pktinfo'
 #define IP6BUFLEN (CMSG_SPACE(sizeof(struct in6_pktinfo)) + \
                                      ^
ipv6.h:214:23: note: in expansion of macro 'IP6BUFLEN'
  unsigned char rcvbuf[IP6BUFLEN];

[1] http://autobuild.buildroot.net/results/523/523858fb930e74fe28f24989ff0697693b5fdd67

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>