Updates on Mar 21, 2026 20:00
------------------------------------------------------------------------------------------
dolphin-emu.mk 0e92a147036fa9ab8a953b40723f43142c2e5d7b # Version: Commits on Mar 21, 2026
------------------------------------------------------------------------------------------
Merge pull request #14488 from Simonx22/android/convert-permissionshandler-to-kotlin

Android: Convert PermissionsHandler to Kotlin,

--------------------------------------------------------------------------------------
openmsx.mk aa6872e087484ec592c0b9a9f7a387124fa047f7 # Version: Commits on Mar 21, 2026
--------------------------------------------------------------------------------------
MSXDev25 roundup and various other adjustments/fixes,

-------------------------------------------------------------------------------------
ppsspp.mk 2d8832ec7169d522945365e153c8fce6cefbb07f # Version: Commits on Mar 21, 2026
-------------------------------------------------------------------------------------
Merge pull request #21392 from chealy/gl-timer-query-profiler

OpenGL: Add GPU timestamp profiling with GL_EXT_disjoint_timer_query,

------------------------------------------------------------------------------------
rpcs3.mk cd1d6282b4d8ddaf46de3af506eb5da69723c0f1 # Version: Commits on Mar 20, 2026
------------------------------------------------------------------------------------
Qt: Remove some unused code,

-------------------------------------------------------------------------------------
snes9x.mk 871a88065ca2d4e218b95626b646742a40cf88ae # Version: Commits on Mar 21, 2026
-------------------------------------------------------------------------------------
gtk: Fix build with -DUSE_SYSTEMZIP in libjma (#1033)

Otherwise build fails with:

  In file included from /var/tmp/portage/games-emulation/snes9x-1.63/work/snes9x-1.63/gtk/../snes9x.h:43,

                   from /var/tmp/portage/games-emulation/snes9x-1.63/work/snes9x-1.63/jma/s9x-jma.cpp:11:

  /var/tmp/portage/games-emulation/snes9x-1.63/work/snes9x-1.63/gtk/../stream.h:54:14: fatal error: unzip.h: No such file or directory

     54 | #    include \unzip.h\

        |              ^~~~~~~~~

  compilation terminated.,

-------------------------------------------------
vice.mk r46030 # Version: Commits on Mar 21, 2026
-------------------------------------------------
null

-------------------------------------------------------------------------------------------
xenia-canary.mk 9a06a19eac017e6e915d1d26236da2926501b30f # Version: Commits on Mar 21, 2026
-------------------------------------------------------------------------------------------
[Testing] Parallel execution for ppc tests on posix

On posix run tests in parallel using a thread pool with fork-per-test

isolation (ported from edge).

On all platforms add progress output showing suite name and test count,

as well as elapsed time in the summary.,

-------------------------------------------------------------------------------------------
xenia-native.mk 9a06a19eac017e6e915d1d26236da2926501b30f # Version: Commits on Mar 21, 2026
-------------------------------------------------------------------------------------------
[Testing] Parallel execution for ppc tests on posix

On posix run tests in parallel using a thread pool with fork-per-test

isolation (ported from edge).

On all platforms add progress output showing suite name and test count,

as well as elapsed time in the summary.,

-------------------------------------------------------------------------------------
ikemen.mk d44b544a837d5b77241bf77960abc0e46e4b1a8d # Version: Commits on Mar 21, 2026
-------------------------------------------------------------------------------------
style: fix code style issues with gofmt,

----------------------------------------------------------------------------------------
rpi-utils.mk d9d1e5f686b0c2b766c7174d4937905414505326 # Version: Commits on Mar 21, 2026
----------------------------------------------------------------------------------------
readme: Add libcurses-dev to the dependencies for rpi-gpu-usage

rpi-gpu-usage depends upon libcurses-dev which is not installed by

default on RPi OS. Update the build instructions to include this in

the dependencies.,

------------------------------------------------------------------------------------
box64.mk 5d9e853496652720f9dc6ec7457fe29ba94b7f0e # Version: Commits on Mar 21, 2026
------------------------------------------------------------------------------------
[WRAPPER] Ported the steam vulkan hack to 64-bit (#3692)

* [WRAPPER] Ported the steam vulkan hack to 64-bit

* fix build,

------------------------------------------------------------------------------------
cdogs.mk fdac3f6d85c937529b32293e91910dca481c932b # Version: Commits on Mar 21, 2026
------------------------------------------------------------------------------------
Sprite variations for bookshelf/plant (fixes #767),

------------------------------------------------------------------------------------------
fallout2-ce.mk b71f1e7d185de763b4fea54ca641be4fedbc9b8d # Version: Commits on Mar 21, 2026
------------------------------------------------------------------------------------------
Merge pull request #313 from NovaRain/wmenc_table_fix

Fix crash/glitched map when the encounter table has no available entries,

------------------------------------------------------------------------------------------------
libretro-mame-src.mk 8d392aaa6a178718a5d268ed694d919b0d910fd7 # Version: Commits on Mar 21, 2026
------------------------------------------------------------------------------------------------
Merge remote-tracking branch 'upstream/master',

----------------------------------------------------------------------------------------
retroarch.mk d251a746e6933a1b161d62bdcfd08d2456e0dd0c # Version: Commits on Mar 21, 2026
----------------------------------------------------------------------------------------
Vulkan: fix menu brightness overriding game brightness in HDR

The game and menu composite HDR pipeline calls shared a single

persistently-mapped UBO buffer. Since both draws are recorded into

one command buffer before GPU submission, the menu composite write

overwrote the game content's BrightnessNits before the GPU executed

either draw â€” causing menu brightness changes to affect game content.

Add a separate ubo_menu buffer for the menu composite draw so each

pipeline call writes to independent GPU memory.

D3D11/D3D12 are unaffected: MAP_WRITE_DISCARD allocates new backing

memory per Map call, so each draw naturally sees its own UBO data.,

----------------------------------------------------------
bgfx.mk v1.142.9190-524 # Version: Commits on Mar 21, 2026
----------------------------------------------------------
deps: bump bgfx to latest,

--------------------------------------------------------------------------------------------
vpinball-next.mk 10cf5b1d0c662e4d11a98d936e8d266c64d2414e # Version: Commits on Mar 21, 2026
--------------------------------------------------------------------------------------------
PUP: fix crash on end of animation, implement blinking animation,

----------------------------------------------------------------------------------------
doomretro.mk 026137a4700aea5513d91eb0bf4f24285dd7c9db # Version: Commits on Mar 21, 2026
----------------------------------------------------------------------------------------
Further fix to alignment of console text,

--------------------------------------------------------------------------------------
vkquake.mk 805c5282e58f97ae9b2e01c93e1a5e6de7d2e2d7 # Version: Commits on Mar 20, 2026
--------------------------------------------------------------------------------------
Readme : Added an Error Reporting guide, removed HOWTOs files from archives,

--------------------------------------------------------------------------------------
yquake2.mk 8d1117d6aba4e359c9af6e191ae6d6a422d7e3d0 # Version: Commits on Mar 21, 2026
--------------------------------------------------------------------------------------
game: fix dynamic fames based move,

----------------------------------------------------------------------------------
trx.mk 6cc02521a439ae79a1ffa27ec16a5faed16b1819 # Version: Commits on Mar 21, 2026
----------------------------------------------------------------------------------
docs: release 1.4,

--------------------------------------------------------------------------------------------------
libretro-clownmdemu.mk 3b278c900c278678763d96087f1d343a6aed6e58 # Version: Commits on Mar 21, 2026
--------------------------------------------------------------------------------------------------
Update common.,

-------------------------------------------------------------------------------------------------
libretro-geargrafx.mk da006ef24a558e6e9e1bf55fc15c9e473a526ca7 # Version: Commits on Mar 21, 2026
-------------------------------------------------------------------------------------------------
Merge branch 'main' of https://github.com/drhelius/Geargrafx,

--------------------------------------------------------------------------------------------------
libretro-gearsystem.mk 68fc7eae4a73e8da91481e252239ee98c3b539d3 # Version: Commits on Mar 21, 2026
--------------------------------------------------------------------------------------------------
Fix hotkey dialog on non-US keyboards,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk 2d8832ec7169d522945365e153c8fce6cefbb07f # Version: Commits on Mar 21, 2026
----------------------------------------------------------------------------------------------
Merge pull request #21392 from chealy/gl-timer-query-profiler

OpenGL: Add GPU timestamp profiling with GL_EXT_disjoint_timer_query,

---------------------------------------------------------------------------------------------
libretro-vba-m.mk 7205d4386b4e9c8a04654dd5de254c39cb04ff46 # Version: Commits on Mar 21, 2026
---------------------------------------------------------------------------------------------
build: check host deps for vcpkg binpkgs installed

Check if host dependencies for vcpkg binary packages are already

installed before checking if they exist in the package list.

Signed-off-by: Rafael Kitover <rkitover@gmail.com>,

----------------------------------------------------------
retrocrisis.mk 20260321 # Version: Commits on Mar 21, 2026
----------------------------------------------------------
SHOWCASE:

- https://youtu.be/hOuYV6IDCpE

___

NOTES:

- Added \VB\ (Virtual Boy)

___

INSTALLATION GUIDES:

- [Windows](https://youtu.be/G42g23ONYsI)

- [iOS](https://youtu.be/2L3fgoabkq0)

- [Linux](https://youtu.be/R12PqZ8LSIY)

- [Steam Deck - Discover Store version](https://youtu.be/Bbr0a6b1qHI)

- [Steam Deck - Steam Store version](https://youtu.be/xKyZ6F7r-54)

___

*Please delete old packs before installing this pack,