package/rt-tests: disable for musl toolchains
The cyclictest program doesn't build with musl toolchains due to
several issues with a different implementation of the "struct sigevent"
from Glibc/uClibc and musl (similar to [1]).

The pi_stress program doesn't build with musl toolchains with the
following error since musl doesn't provide _POSIX_THREAD_PRIO_INHERIT
define even if musl have Priority Inheritance mutexes [2]:

src/pi_tests/pi_stress.c:78:2: error: #error "Can't run this test without PI Mutex support"
 #error "Can't run this test without PI Mutex support"

Since the fix for cyclictest is not trivial, disable rt-tests for musl
toolchains.

Fixes:
http://autobuild.buildroot.net/results/c27/c272ef7df6190cbb688e6db0b1ee210e6fbb472c

[1] https://bugs.mysql.com/bug.php?id=80322
[2] http://www.openwall.com/lists/musl/2016/03/18/6

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>