xapp_xinit: depends on MMU
Fixes http://sysmic.org/~jezz/results/8b5af679:

xinit.o: In function `_main':
xinit.c:(.text+0x65e): undefined reference to `_fork'
xinit.c:(.text+0x7d4): undefined reference to `_fork'
collect2: ld returned 1 exit status

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>