dmraid: exclude nios2 sourcery toolchains, _gp issue
Fixes:

  http://autobuild.buildroot.net/results/a7e2631d06634d768faf5c1d02712cc9b38562c6/

Investigation of nios2 config.log shows that this is caused by the
"infamous" _gp link issue on codesourcery toolchains:

configure:9118: /ssd1/thomas/autobuild/instance-0/output/host/usr/bin/nios2-linux-gnu-gcc -o conftest -O2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64    conftest.c -ldevmapper-event   >&5
/ssd1/thomas/autobuild/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/nios2-linux-gnu/4.8.3/../../../../nios2-linux-gnu/bin/ld: /ssd1/thomas/autobuild/instance-0/output/host/usr/nios2-buildroot-linux-gnu/sysroot/usr/lib/crt1.o: undefined reference to symbol '_gp'
/ssd1/thomas/autobuild/instance-0/output/host/usr/nios2-buildroot-linux-gnu/sysroot/usr/lib/libdevmapper.so.1.02: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

As with other cases, fixed by disabling this package when codesourcery
toolchains are in use.

Signed-off-by: Brendan Heading <brendanheading@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>