olimex_a20_olinuxino_micro: bump to U-Boot 2017.5 and fix build
This defconfig does not build anymore since commit
e054d07931dc4571b2dc19202ab8359fc0199921 ("package/gcc: switch to gcc
6.x as the default"). Fix by upgrading to the latest U-Boot version.

Fixes:
  In file included from include/linux/compiler.h:54:0,
                   from include/linux/bitops.h:5,
                   from ./include/common.h:20:
  include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
   #include gcc_header(__GNUC__)
                                ^
  compilation terminated.

[Build- and run-tested]
Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>