Updates on Mar 01, 2025 13:05
------------------------------------------------------------------------------------------
duckstation.mk a0fef2d5abc50d6306eeff20725c9c3ff9d4afdd # Version: Commits on Mar 01, 2025
------------------------------------------------------------------------------------------
Qt: Merge gamelistmodel.cpp and gamelistwidget.cpp

They're constantly referring to each other.,

--------------------------------------------------------------------------------------
openmsx.mk 002e021602dd1d087f2d3a63fac4f305cdb8f6c1 # Version: Commits on Mar 01, 2025
--------------------------------------------------------------------------------------
Fix changes-highlighting in debugger on step-back

This finishes:

    Missing display of changed values in another color (red) after stepping

    https://github.com/openMSX/openMSX/issues/1657,

------------------------------------------------------------------------------------
rpcs3.mk af23df842d168923f515f2307feaa7495b78e7cc # Version: Commits on Mar 01, 2025
------------------------------------------------------------------------------------
PPU: Report encrypted modules with KLIC in main file, opportunistic compilation at exit-spawn (#16743),

-------------------------------------------------
vice.mk r45510 # Version: Commits on Mar 01, 2025
-------------------------------------------------
Gtk3: Fix non-ASCII codes appearing in the clipboard with \Edit\ -> \Copy\

See bug #2087.

git-svn-id: https://svn.code.sf.net/p/vice-emu/code/trunk@45510 379a1393-f5fb-40a0-bcee-ef074d9b53f7,

----------------------------------------------------------------------------------
stk.mk c616a1d0263ee1932fddb090f9a02e292ab99220 # Version: Commits on Mar 01, 2025
----------------------------------------------------------------------------------
src/network/protocols/ranking.hpp: add missing `<stdint.h>` include (#5346)

Without the chnage the build fails on upcoming `gcc-15` as:

    /build/source/src/network/protocols/ranking.hpp:31:5: error: 'uint32_t' does not name a type

       31 |     uint32_t online_id;

          |     ^~~~~~~~,

----------------------------------------------------------------------------------------
retroarch.mk 5c92055aefcfa4396c72a4b7c162144ea02e3057 # Version: Commits on Mar 01, 2025
----------------------------------------------------------------------------------------
Fix cloud sync driver menu item refresh,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk 6c9d5bc1fbc63838dd9fed8a7e094abf27a5b729 # Version: Commits on Mar 01, 2025
------------------------------------------------------------------------------------------
engine: server: cleanup penalties and warns for new players,