gcc: fix libsanitizer build with _FILE_OFFSET_BITS=64
After the commit b8512ed25aef1c17 "gcc: preserve CXXFLAGS_FOR_TARGET"
target CFLAGS are passed to all libraries bundled with gcc. This breaks
libsanitizer on gcc-4.9.x when building with _FILE_OFFSET_BITS=64:

  error: size of array ‘assertion_failed__837’ is negative
  ...
  libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:837:1:
  note: in expansion of macro ‘CHECK_SIZE_AND_OFFSET’
  CHECK_SIZE_AND_OFFSET(dirent, d_ino);

This issue is fixed in the libsanitizer mainline and in gcc-5.x.
There's no issue with gcc-4.8.x and earlier.

Reported-by: Julien CORJON <corjon.j@ecagroup.com>
Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>
Backported from: https://llvm.org/svn/llvm-project/compiler-rt/trunk@220328
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>