libedit: fix build error with musl toolchain
Libedit build fails when __STDC_ISO_10646__ is not defined, and that is
the case when compiling with musl toolchains.

chartype.h:52:3: error: #error wchar_t must store ISO 10646 characters
  #error wchar_t must store ISO 10646 characters
   ^

Musl is ISO 10646 compliant but doesn't define __STDC_ISO_10646__, so
let's define it manually.

Fixes:
http://autobuild.buildroot.net/results/3d12a7e6423d236c9d528bca7cbcf86b1499d738/
http://autobuild.buildroot.net/results/b92f7e2b86ffa575d8a8a0b91fbdd9bcb0f231de/
http://autobuild.buildroot.net/results/c476a48936f8810117bb292fb0d8a43c09068de6/
http://autobuild.buildroot.net/results/a30bb1423cc92137a2deaec0a32c7df947384d49/

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>
Tested-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>