package/dtc: additional fix of include guards for older u-boot
With recent dtc but old u-boot, compilation issues occur related to libfdt.
These problems really are u-boot issue since it does not properly set
include paths so that its own headers are included. Nevertheless, since the
u-boot version is typically decided by users and stuck at some version
provided by a SoC or board vendor, it is not feasible to fix those old
versions.

Instead, already several fixes were made in the past, in Buildroot.
See commits:

72929456676 "package/dtc: fix include guards for older kernel/u-boot"
05df311debe "uboot: fix build for older uboot source trees"
7fb54f6a92a "uboot: fix build when libfdt-devel is installed system-wide"
3afb5cf0195 "uboot: ensure host includes are searched before system default
                includes"
2301f21c421 "uboot: revert "uboot: use local libfdt.h""
3e2d7ac1e39 "uboot: use local fdt headers"
f5655c9af26 "uboot: use local libfdt.h"

Commit 72929456676611c6422f3302f4e95f6f58a1d44a fixes the problem caused by
dtc having changed their include guards from _FOO_H to FOO_H (leading
underscore removed). Old u-boot would still use _FOO_H, which (combined with
host-dtc headers that use FOO_H) would cause the inclusion of two different
copies of the same nominal include file, e.g. libfdt.h or libfdt_env.h,
causing 'error: redefinition of xxx' compilation issues.
The fix sets the 'new' include guard when the 'old' one is detected,
preventing a second inclusion of the same nominal file.

For some u-boot versions, however, this change not only needs to be made in
libfdt.h and libfdt_env.h, but also in 'fdt.h'.

Update the dtc patch to do just that.

Signed-off-by: Thomas De Schampheleire <thomas.de_schampheleire@nokia.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>