Updates on Jun 12, 2025 20:07
--------------------------------------------------------------------------------------
openmsx.mk 19646b811206dac674a9981d56373419ca7192a2 # Version: Commits on Jun 12, 2025
--------------------------------------------------------------------------------------
Update manual for screenshot command.

Missed that in the PR... oops.,

----------------------------------------------------
pcsx2.mk v2.3.416 # Version: Commits on Jun 12, 2025
----------------------------------------------------
- GS/HW: Fix possible null reference causing a crash

-------------------------------------------------------------------------------------
ppsspp.mk 986eac71dca031655ff045fcf09206058808f7ba # Version: Commits on Jun 12, 2025
-------------------------------------------------------------------------------------
Merge pull request #20511 from hrydgard/sasaudio-dont-reset

SasAudio: Don't reset the decoder on SetVoice if all params are the same,

------------------------------------------------------------------------------------
rpcs3.mk 2b7161208ec4c923b8d1f2d37ce8665bb7414053 # Version: Commits on Jun 12, 2025
------------------------------------------------------------------------------------
[CI] FreeBSD build (#17293)

Build FreeBSD on Github Actions,

---------------------------------------------------------------
ruffle.mk nightly-2025-06-12 # Version: Commits on Jun 12, 2025
---------------------------------------------------------------
## What's Changed

* avm1: Simplify register access in `Activation` by @moulins in https://github.com/ruffle-rs/ruffle/pull/20602

**Full Changelog**: https://github.com/ruffle-rs/ruffle/compare/nightly-2025-06-11...nightly-2025-06-12,

----------------------------------------------------
ryujinx.mk 1.3.87 # Version: Commits on Jun 11, 2025
----------------------------------------------------
Canary-1.3.87

--------------------------------------------------------------------------------------
shadps4.mk 226058d2e97f353d777032a74db89b1e0de91948 # Version: Commits on Jun 12, 2025
--------------------------------------------------------------------------------------
fixed nonload issues with background music (#3094),

---------------------------------------------------------------------------------------------
solarus-engine.mk 3214cf75761e06a62cde261be3f9334d4d884e2e # Version: Commits on Jun 12, 2025
---------------------------------------------------------------------------------------------
Merge branch 'stairs-subtype-lua-methods' into 'dev'

---------------------------------------------------------------------------------------
thextech.mk 3e870fc2a2c6f477e7371660b1d4a68590df309a # Version: Commits on Jun 11, 2025
---------------------------------------------------------------------------------------
vita-ci.vpk: push bare vpk to thextech-vitadb-nightly.vpk,

----------------------------------------------------------------------------------------
pironman5.mk b8f44c63437cae7ad9ea665bcd04f14c1c3ee852 # Version: Commits on Jun 12, 2025
----------------------------------------------------------------------------------------
refactor: update version and improve installation scripts

- Bump version to 1.2.13.4

- Add error handling and unzip dependency to install_lgpio.sh

- Rename fan_settings to gpio_settings for broader peripheral support

- Remove commented out apt_dependencies in install.py,

------------------------------------------------------------------------------------
box64.mk 0d10035ffd2de39febff3847b6bface88c279ba1 # Version: Commits on Jun 12, 2025
------------------------------------------------------------------------------------
[ARM64_DYNAREC] Fixed some typos related ymm unneeded tracing (helps #2724) (#2735),

---------------------------------------------------------------------------------------
corsixth.mk 320ae52d7bc65b3cca24478797b592968018ff77 # Version: Commits on Jun 12, 2025
---------------------------------------------------------------------------------------
Merge pull request #2907 from lewri/grim_no_dynamic_info

Give GrimReaper empty updateDynamicInfo,

---------------------------------------------------------------------------------------
etlegacy.mk f39fdd080582849b29df0855ad08105dab17ab96 # Version: Commits on Jun 12, 2025
---------------------------------------------------------------------------------------
misc: Collect-and-check considers 'win64' warnings non-pertinent

For now. Due to dozens of:

Error: win64 - D:\\a\\etlegacy\\etlegacy\\src\\qcommon\\q_shared.c(1563,10): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data [D:\\a\\etlegacy\\etlegacy\\build\\ui.vcxproj]

Type warnings.,

------------------------------------------------------------------------------------------
fallout2-ce.mk 3d2aced2f770c69746af6553284f9916dcb32003 # Version: Commits on Jun 12, 2025
------------------------------------------------------------------------------------------
Merge pull request #149 from fallout2-ce/worldmap-fallout1-trail-feature

Worldmap Fallout1 trail Feature,

----------------------------------------------------------------------------------------
supertux2.mk 9ff3bbcc1a337fc943ee2742eb5544a2f3973daa # Version: Commits on Jun 12, 2025
----------------------------------------------------------------------------------------
Change the icon of Tilemaps based on their attributes (#3282)

* Add `Tilemap` icon variants

Co-authored-by: Frostwithasideofsalt <60326522+Frostwithasideofsalt@users.noreply.github.com>

* Add tilemap icons based on attributes

* Indentation

* Fix icons for tilemaps on paths

* Unnecessary changes

---------

Co-authored-by: Frostwithasideofsalt <60326522+Frostwithasideofsalt@users.noreply.github.com>,

-----------------------------------------------------------------------------------------
winetricks.mk 9e29aa7e2d8e84880aec741ed92eed35baa742ac # Version: Commits on May 31, 2025
-----------------------------------------------------------------------------------------
w_try_7z: Fixup,

----------------------------------------------------------------------------------------
retroarch.mk 9d09ec3478c97243044f89912012bb6ad92966e2 # Version: Commits on Jun 12, 2025
----------------------------------------------------------------------------------------
Show undo save/load state items order non-submenu addition,

-----------------------------------------------------------------------------------------
libdmdutil.mk c7530fb5766aad61ead9083250338fdb1bb880f3 # Version: Commits on Jun 12, 2025
-----------------------------------------------------------------------------------------
allow local displays when forwarding to dmdserver (#79),

-------------------------------------------------------------------------------------
gzdoom.mk e435a4ef649585d47c3e29ca626312f49c7012d8 # Version: Commits on Jun 12, 2025
-------------------------------------------------------------------------------------
Fixed player assignments when loading multiple players,

--------------------------------------------------------------------------------------
vkquake.mk 19c16854cc0cc567840c067be00f0b971e708526 # Version: Commits on Jun 12, 2025
--------------------------------------------------------------------------------------
f@#k clang-format..,

-----------------------------------------------------------------------------------
tr1x.mk 5ec0fe04b025dc334f31eb35510a70d0ec600c4b # Version: Commits on Jun 12, 2025
-----------------------------------------------------------------------------------
lara: adopt burn flag in TR1

This updates TR1 to use the same approach as TR2 in tracking

Lara's burn status, saving it separately in savegame files to work

independently of having effect saving on. In addition, this merges

Lara's logic for catching fire and putting flames out into TRX.

Resolves #3157.,

-----------------------------------------------------------------------------------
tr2x.mk 5ec0fe04b025dc334f31eb35510a70d0ec600c4b # Version: Commits on Jun 12, 2025
-----------------------------------------------------------------------------------
lara: adopt burn flag in TR1

This updates TR1 to use the same approach as TR2 in tracking

Lara's burn status, saving it separately in savegame files to work

independently of having effect saving on. In addition, this merges

Lara's logic for catching fire and putting flames out into TRX.

Resolves #3157.,

---------------------------------------------------------------------------------------------
libretro-fbneo.mk e8291a39f637d23900d6998ea7f67648856201f9 # Version: Commits on Jun 12, 2025
---------------------------------------------------------------------------------------------
(libretro) update files,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk 986eac71dca031655ff045fcf09206058808f7ba # Version: Commits on Jun 12, 2025
----------------------------------------------------------------------------------------------
Merge pull request #20511 from hrydgard/sasaudio-dont-reset

SasAudio: Don't reset the decoder on SetVoice if all params are the same,

----------------------------------------------------------------------------------------------
libretro-stella.mk ee0b96cd87710ad19aa47156d39df5a92c156a34 # Version: Commits on Jun 12, 2025
----------------------------------------------------------------------------------------------
De-duplicate some cart names (#1080),