beecrypt: unconditionally disable openpm
beecrypt does not properly handle its dependency on openpm, so that
applications using libbeecrypt are not aware that they also need openmp
(libgomp). This causes error messages during linking, such as (rpm):

..-gcc [..] -lbeecrypt  -lbz2 -lz -lpopt -lpthread
libbecrypt.so: undefined reference to `GOMP_sections_end_nowait'
libbecrypt.so: undefined reference to `GOMP_parallel_end'
libbecrypt.so: undefined reference to `GOMP_sections_next'
libbecrypt.so: undefined reference to `GOMP_parallel_sections_start'

Because the openpm dependency of beecrypt is only used by rsa.c, to
parallelize the calculation of RSA cyphers, we can simply disable openmp in
beecrypt instead of trying to fix the way -lgomp is passed.

Fixes http://autobuild.buildroot.net/results/bcf/bcff4b81bfbb1191f97317b0945c74d948c9774b/

Signed-off-by: Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>