Updates on Jun 26, 2025 18:48
-----------------------------------------------------------------------------------
cemu.mk 0a121c97c79d329caa027e21714737a70cef80dd # Version: Commits on Jun 26, 2025
-----------------------------------------------------------------------------------
Input: Detect Classic Controller Pro as Classic Controller (#1614),

--------------------------------------------------------------------------------------
melonds.mk 7b562f71b301e5475d35bf95f06c6fd14b09559c # Version: Commits on Jun 25, 2025
--------------------------------------------------------------------------------------
NDMA: fix IRQ in infinite repeat mode,

--------------------------------------------------------------------------------------
openmsx.mk d6f573ea88a980e2b8e78bb4495052cd91e97751 # Version: Commits on Jun 25, 2025
--------------------------------------------------------------------------------------
[2/2] Simplify passing EmuDuration/EmuTime,

----------------------------------------------------
pcsx2.mk v2.3.452 # Version: Commits on Jun 26, 2025
----------------------------------------------------
- [GameDB: The Golden Compass fixes](https://github.com/PCSX2/pcsx2/pull/12918)

-------------------------------------------------------------------------------------
ppsspp.mk ce64ae2f7bb3a1d0eca834678e0a51f3bf07b4e2 # Version: Commits on Jun 26, 2025
-------------------------------------------------------------------------------------
Merge pull request #20574 from hrydgard/ffii-copy-texture-fix

Make the check for framebuffer copy targets slightly more lenient for tiny copies.,

------------------------------------------------------------------------------------
rpcs3.mk aa50b0fbb99c04918645a78acd1fcab8a1cf31b2 # Version: Commits on Jun 24, 2025
------------------------------------------------------------------------------------
vk: Fix video-out calibration pass inputs,

---------------------------------------------------------------
ruffle.mk nightly-2025-06-26 # Version: Commits on Jun 26, 2025
---------------------------------------------------------------
## What's Changed

* pixelbender: Various fixes related to returning values by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/20827

* build(deps): bump the winit-wgpu-egui group with 4 updates by @dependabot in https://github.com/ruffle-rs/ruffle/pull/20821

**Full Changelog**: https://github.com/ruffle-rs/ruffle/compare/nightly-2025-06-25...nightly-2025-06-26,

--------------------------------------------------------------------------------------
shadps4.mk 0a58ead5f6bf9b0c98c4a017788903f5920bde9d # Version: Commits on Jun 26, 2025
--------------------------------------------------------------------------------------
Add alternate code paths for handling legacy struct behavior in sceVideodec2GetPictureInfo (#3154)

Older games aren't fond of how our sceVideodec2GetPictureInfo implementation outputs AVC picture info after the struct size increase.

Adding the old struct, and additional code using it for these games works around this problem.,

-----------------------------------------------------------------------------------
ymir.mk 19d05d3ae6f07c4ada2d5b0756178f5f17accc96 # Version: Commits on Jun 25, 2025
-----------------------------------------------------------------------------------
feat(system): Allow reducing emulation timeslices to the minimum possible to tighten synchronization between components,

------------------------------------------------------------------------------------
box64.mk d57416f4fb2b75a573e9731c1b33d0c9a1bea234 # Version: Commits on Jun 26, 2025
------------------------------------------------------------------------------------
[LA64_DYNAREC] Removed some redundant macro definitions (#2778),

-------------------------------------------------------------------------------------------
jazz2-native.mk 149b5c4db0e2182c54ebead4e9f5a6022b84ecc8 # Version: Commits on Jun 26, 2025
-------------------------------------------------------------------------------------------
Fixed build,

----------------------------------------------------------------------------------------
openmohaa.mk 854d24138e470b4d13ce9d5dc2b7a96dd8c249e7 # Version: Commits on Jun 25, 2025
----------------------------------------------------------------------------------------
Improve bot attack to reduce the difficulty

- Bigger aim offset

- Burst fire

- Random reaction time based on enemy distance,

-----------------------------------------------------------------------------------
rott.mk 98fc7df6828d4b5609c776e12496a82bd87b5e2c # Version: Commits on Jun 26, 2025
-----------------------------------------------------------------------------------
Show game engine (project) version on startup (#99)

* Show game engine (project) version on startup

* build: resolve compiler warnings

rott/rt_main.c: In function â€˜DrawRottTitleâ€™:

rott/rt_main.c:371:9: error: unused variable â€˜bufâ€™ [-Werror=unused-variable]

  371 |    char buf[5];,

----------------------------------------------------------------------------------------
retroarch.mk 6dcb727c62740ec21916e61fde08c5ef29891030 # Version: Commits on Jun 26, 2025
----------------------------------------------------------------------------------------
Remove unused buffer (?),

-------------------------------------------------------------------------------------
gzdoom.mk c36ea479a809028e2f53224227b924a3c8f31742 # Version: Commits on Jun 25, 2025
-------------------------------------------------------------------------------------
Move engine verification to front end

This can't be in the backend since it uses game-specific information.,

-----------------------------------------------------------------------------------
tr1x.mk bc30f7f2df30f6e97eaa15096305fc3df3783302 # Version: Commits on Jun 26, 2025
-----------------------------------------------------------------------------------
tr1/objects/save_crystal: add underwater functionality

This updates save crystals so that collision tests are performed when

Lara is underwater.

Resolves #3356.,

-----------------------------------------------------------------------------------
tr2x.mk bc30f7f2df30f6e97eaa15096305fc3df3783302 # Version: Commits on Jun 26, 2025
-----------------------------------------------------------------------------------
tr1/objects/save_crystal: add underwater functionality

This updates save crystals so that collision tests are performed when

Lara is underwater.

Resolves #3356.,

---------------------------------------------------------------------------------------------
libretro-fbneo.mk 44df43eaa72e2fc12517b463e89a54e3a32a9195 # Version: Commits on Jun 26, 2025
---------------------------------------------------------------------------------------------
(libretro) update files,

-------------------------------------------------------------------------------------------------
libretro-geargrafx.mk 82c704395b4ad932952e1e5f0ec8f63a09e197e1 # Version: Commits on Jun 26, 2025
-------------------------------------------------------------------------------------------------
Update readme,

----------------------------------------------------------------------------------------------
libretro-p2000t.mk 3c66973638277f80c340ed47cd206d786e5cf41d # Version: Commits on Jun 26, 2025
----------------------------------------------------------------------------------------------
Update README.md,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk ce64ae2f7bb3a1d0eca834678e0a51f3bf07b4e2 # Version: Commits on Jun 26, 2025
----------------------------------------------------------------------------------------------
Merge pull request #20574 from hrydgard/ffii-copy-texture-fix

Make the check for framebuffer copy targets slightly more lenient for tiny copies.,

----------------------------------------------------------------------------------------------
libretro-stella.mk c4afcbae32556127c7fa97d86c5e2f9b9f5e891a # Version: Commits on Jun 26, 2025
----------------------------------------------------------------------------------------------
small libretro follow-on fixes (#1085)

* add missing gitignore

* split paddles and rearrange core option,

---------------------------------------------------------------------------------------------
libretro-vba-m.mk a97a6879d94fd47a7dc4cb24a2eb4667fd0da183 # Version: Commits on Jun 26, 2025
---------------------------------------------------------------------------------------------
Add 7z windows header,

--------------------------------------------------------------------------------------------
libretro-vice.mk c8f8c0a99619547a8a3918dc7bf1e7f5d6cd08a9 # Version: Commits on Jun 26, 2025
--------------------------------------------------------------------------------------------
Handle GMod2 cart eeprom saves,