shairport-sync: fix non-existent meta_dir member of shairport_cfg struct
shairport-sync tries to access to a non-existent member called
"meta_dir" of a "shairport_cfg" struct:

[snip]
if (config.meta_dir)
[snip]

That struct doesn't have that member so it causes a build failure like
this one:

mdns_tinysvcmdns.c: In function 'mdns_tinysvcmdns_register':
mdns_tinysvcmdns.c:121:13: error: 'shairport_cfg' has no member named
'meta_dir'
if (config.meta_dir)

This issue has been reported and fixed upstream:

  https://github.com/mikebrady/shairport-sync/issues/128#issuecomment-141947175

Fixes:

  http://autobuild.buildroot.net/results/89d/89d22ba2d41e05b407cde04c7e57510b36973ce9/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>