package/libtirpc: fix undefined reference to _authdes_seccreate
Commit d9eff4809977135a285bbc6e7e8c9ec1820ef229 disables the C files auth_des.c
and authdes_prot.c implementing DES authentification but forgets to remove
a function call to authdes_seccreate() in rpc_soc.c.

We add a seperate patch to disable the DES authentification (and not disable it
together with NIS). DES is not provided by uClibc and musl.

Fixes:
http://autobuild.buildroot.org/results/33f/33f1849c6d1441d8565835872281e33a980aba6f/
http://autobuild.buildroot.net/results/02e/02e9321b54d41b4b5c91d93c9942499a20d26919/

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Tested-by: Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
Tested-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Reviewed-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>