package/ruby: enable openssl for host-ruby
Openssl is required so that Gem can install ruby gems from secure websites.

ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or
use non-HTTPS sources

Signed-off-by: Nicolas Carrier <nicolas.carrier@orolia.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>