libcdio: disable on ARC, triggers a toolchain bug
libcdio doesn't build on ARC, with the following compiler error:

iso9660.c:155:1: error: unrecognized supposed constant
[...]
iso9660.c:155:1: internal compiler error: in arc_legitimate_constant_p, at config/arc/arc.c:6028
Please submit a full bug report,

Since this has been happening for a while and is quite noisy in the
autobuilders results, we disable this package on ARC.

Fixes:

  http://autobuild.buildroot.net/results/e837737abaea851bea428a35ea9d3395a6565c54/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>