package/qwt: needs qt5base gui support
In commit b9d761bccd6e781353e9a90ddaead3c8aa69f052 ("package/qwt:
remove qt4 support"), the following line was incorrectly dropped:

  select BR2_PACKAGE_QT5BASE_GUI if BR2_PACKAGE_QT5

Due to this, qt5base can now be configured with widgets enabled but
gui disabled, causing the following build issue:

  ERROR: Feature 'widgets' was enabled, but the pre-condition 'features.gui' failed.

Re-introduce the proper select, but slightly simplified since only Qt5
is supported now.

Fixes:

  http://autobuild.buildroot.net/results/c771c2d5aac3e21f908e5a118f3755dbc9301a47

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
[Thomas: rework commit log]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>