Updates on Mar 06, 2025 18:20
------------------------------------------------------------------------------------------
libfreeaptx.mk 6dee419f934ec781e531f885f7e8e740752e67d1 # Version: Commits on Mar 05, 2025
------------------------------------------------------------------------------------------
Update 0.2.2 - Fix build regression,

--------------------------------------------------------------------------------------------------------
batocera-emulationstation.mk d710b525f9360ab8265e14daec779564736294db # Version: Commits on Mar 06, 2025
--------------------------------------------------------------------------------------------------------
update po

Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>,

------------------------------------------------------------------------------------------------
batocera-es-piboy.mk d710b525f9360ab8265e14daec779564736294db # Version: Commits on Mar 06, 2025
------------------------------------------------------------------------------------------------
update po

Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>,

---------------------------------------------------------------------------------------
amiberry.mk 623140444db696d4032154dad58894640fa2f134 # Version: Commits on Mar 06, 2025
---------------------------------------------------------------------------------------
Bump version to 7.0.6,

-------------------------------------------------------------------------------------
azahar.mk cc81fdec3d3187beb6a3ae41c5cb6bf3fb2d7af7 # Version: Commits on Mar 06, 2025
-------------------------------------------------------------------------------------
Corrected some incorrect strings,

-----------------------------------------------------------------------------------
cemu.mk 31d2db6f78a72feda9e3804060eb4364188c8553 # Version: Commits on Mar 04, 2025
-----------------------------------------------------------------------------------
OpenGL: Add explicit/matching qualifiers in output shader interface

fixes issues with old intel drivers,

------------------------------------------------------------------------------------------
dolphin-emu.mk 99e686de34c2c862a01ee3859abb4b3256f04a63 # Version: Commits on Mar 05, 2025
------------------------------------------------------------------------------------------
Merge pull request #13393 from luzpaz/dbz

GraphicMods: Fix typo in DBZ Budokai Tenkaichi 3/metadata.json,

------------------------------------------------------------------------------------------
duckstation.mk 826f10239ce69b573dba83e5c70d866a292434b5 # Version: Commits on Mar 06, 2025
------------------------------------------------------------------------------------------
CPU/Recompiler: Flush GTE completion cycle on load without fastmem,

--------------------------------------------------------------------------------------
flycast.mk 562f78cd71bdd3687b4054d3782f3df523d5aff9 # Version: Commits on Mar 05, 2025
--------------------------------------------------------------------------------------
libretro: build osx-x64 build on new builder,

-------------------------------------------------------------------------------------
ikemen.mk c6329133eb4cbeef3158604d5238589688cba280 # Version: Commits on Mar 06, 2025
-------------------------------------------------------------------------------------
Merge pull request #2350 from potsmugen/fix_merged

fix: HitBy, TargetBind; refactor Z parameters,

--------------------------------------------------------------------------------------
openmsx.mk bc76158e274a6e7afcaa210a7719d573415d959f # Version: Commits on Mar 06, 2025
--------------------------------------------------------------------------------------
No longer generate '#define ASM_X86...' in 'build-info.hh'

It's not used anymore (hasn't been for a while). Instead of writing asm

code we prefer to use intrinsics now. Or even better plain c++ code

(with modern compilers, the performance difference with manually written

asm code is often neglible or even negative).,

-------------------------------------------------------------------------------------
ppsspp.mk 02734b03a1cde31f02fc4f6c1591da39a9a39881 # Version: Commits on Mar 06, 2025
-------------------------------------------------------------------------------------
Merge pull request #20080 from hrydgard/framedump-issues

Fix some framedump playback issues,

---------------------------------------------------------------
ruffle.mk nightly-2025-03-06 # Version: Commits on Mar 06, 2025
---------------------------------------------------------------
## What's Changed

* core: Replace `GcCell` with `Gc` in `Bitmap` by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/19709

* core: Replace `GcCell` with `Gc` in `LoaderDisplay` & `MorphShape` by @kjarosh in https://github.com/ruffle-rs/ruffle/pull/19710

* avm1: Remove all uses of static strings in tests code by @Lord-McSweeney in https://github.com/ruffle-rs/ruffle/pull/19660

* chore: Bump `egui` to `0.31.1`, switch back to mainline `wgpu` `24.0.2` by @torokati44 in https://github.com/ruffle-rs/ruffle/pull/19714

**Full Changelog**: https://github.com/ruffle-rs/ruffle/compare/nightly-2025-03-05...nightly-2025-03-06,

-----------------------------------------------------
ryujinx.mk 1.2.440 # Version: Commits on Mar 06, 2025
-----------------------------------------------------
# Canary builds:

These builds are experimental and may sometimes not work, use [regular builds](https://github.com/Ryubing/Ryujinx/releases/latest) instead if that sounds like something you don't want to deal with.

| Platform | Artifact |

|--|--|

| Windows 64-bit | [Canary Windows Artifact](https://github.com/Ryubing/Canary-Releases/releases/download/1.2.440/ryujinx-canary-1.2.440-win_x64.zip) |

| Linux 64-bit | [Canary Linux Artifact](https://github.com/Ryubing/Canary-Releases/releases/download/1.2.440/ryujinx-canary-1.2.440-linux_x64.tar.gz) |

| Linux ARM 64-bit | [Canary Linux ARM Artifact](https://github.com/Ryubing/Canary-Releases/releases/download/1.2.440/ryujinx-canary-1.2.440-linux_arm64.tar.gz) |

| macOS | [Canary macOS Artifact](https://github.com/Ryubing/Canary-Releases/releases/download/1.2.440/ryujinx-canary-1.2.440-macos_universal.app.tar.gz) |

**Full Changelog**: https://github.com/Ryubing/Ryujinx/compare/Canary-1.2.439...Canary-1.2.440

--------------------------------------------------------------------------------------
shadps4.mk 8b7eed3ffc9835886b088f6c1b0595948bce4c8d # Version: Commits on Mar 06, 2025
--------------------------------------------------------------------------------------
[ci skip] Qt GUI: Update Translation. (#2607)

Co-authored-by: georgemoralis <4313123+georgemoralis@users.noreply.github.com>,

-----------------------------------------------------------------------------------
xemu.mk 046d127f31bad089decc2e213dc8488c43aa6f04 # Version: Commits on Mar 06, 2025
-----------------------------------------------------------------------------------
ui: Trim FontAwesome font to glyphs in use (save 940KiB),

--------------------------------------------------------------------------------------------
xenia-native.mk ccf7adf0151cdd7f056dafc2f537f314643a147d # Version: Commits on Sept 01, 2024
--------------------------------------------------------------------------------------------
[XAM/APP] Recording more Xam app messages

- Recording more xam app messages for future reference

- Removed mistakes from messenger_app.h

- Added missing buffer_ptr, buffer_length to unknown message id logs,

-----------------------------------------------------------------------------------------
rpi-eeprom.mk 3a16bd016f533877079c3bfad188539abd31fb8a # Version: Commits on Feb 24, 2025
-----------------------------------------------------------------------------------------
rpi-eeprom-digest: support specifying keys via PKCS#11 URI

In production setups, it is quite normal that the private key does not

exist as a file in the file system, but is kept inside some HSM,

remote signing service or similar, and only accessed via some pkcs#11

interface; moreover, by design, the private key _cannot_ be extracted

from the HSM or signing service.

In such a case, the user will have set OPENSSL_CONF to some

configuration file setting up the appropriate engine, and the \key\ is

simply the pkcs#11 URI, e.g. \pkcs11:model=foo;object=bar\.

In order to support this use case, automatically infer the appropriate

options to pass to openssl-dgst if \${KEY}\ begins with

\pkcs11:\. Doing this at the top level avoids duplicating the logic in

both writeSig and verifySig. While here, this also adds a sanity check

that -v can only be used while also providing a (public) key to check

against.

This drops the -keyform argument in the non-pkcs#11 case, as openssl

automatically infers the type, and this then in fact allows one to use

a private key in e.g. DER format.

Signed-off-by: Rasmus Villemoes <ravi@prevas.dk>,

-------------------------------------------------------------------------------------------
sdl12-compat.mk 60ba97c41e53dfa34f50eb4741c3a758739623d1 # Version: Commits on Mar 05, 2025
-------------------------------------------------------------------------------------------
video: Reflect SDL12_RESIZABLE in SDL12_Surface->flags

Code depends on being able to see the RESIZABLE flag in video surfaces.

For example, the Perl module SDLx::App will throw an error if it tries to

resize a surface but doesn't find SDL_RESIZABLE in its flags:

     https://metacpan.org/release/FROGGS/SDL-2.548/source/lib/SDLx/App.pm#L143

To improve compatibility with such code, copy the flag to the

VideoSurface12 created in SDL_SetVideoMode.,

------------------------------------------------------------------------------------
box64.mk eb039c0449641264122374a5cb0ea6cc6b47f625 # Version: Commits on Mar 06, 2025
------------------------------------------------------------------------------------
Fix undefined reference to `epoll_pwait2' for LA64 ABI 1.0 (#2422),

------------------------------------------------------------------------------------
cdogs.mk 3c7e80b13091d23b9c13405538ece8ccaf2e5ad6 # Version: Commits on Mar 06, 2025
------------------------------------------------------------------------------------
Base64 encode high score entries #151

Also include explosives in favourites,

------------------------------------------------------------------------------------------
devilutionx.mk ec9f8ff68541b30caed6cf67d3d4996cb15f5358 # Version: Commits on Feb 10, 2025
------------------------------------------------------------------------------------------
Fix issue with Hellfire items morphing when transferred to Diablo,

---------------------------------------------------------------------------------------
etlegacy.mk 2b5aebb3bb5896f379f5fd29072411400197e5f4 # Version: Commits on Mar 06, 2025
---------------------------------------------------------------------------------------
Merge branch 'master' of https://github.com/etlegacy/etlegacy,

-------------------------------------------------------------------------------------------
jazz2-native.mk 11a6d66e3ae5c781a32e63bcd94f10f94f5d4415 # Version: Commits on Mar 06, 2025
-------------------------------------------------------------------------------------------
Minor changes,

----------------------------------------------------------------------------------------
retroarch.mk a6316465a39325157488d862bb914fe549eaad35 # Version: Commits on Mar 06, 2025
----------------------------------------------------------------------------------------
Fetch translations from Crowdin,

---------------------------------------------------------------------------------------
vpinball.mk ececff7d0105d52c18872cbf0a84d0840408fc29 # Version: Commits on Jul 23, 2024
---------------------------------------------------------------------------------------
misc: standalone builds for macos, ios, tvos, android, linux, and rpi,

-------------------------------------------------------------------------------------
gzdoom.mk b0889b98147612f1a4363561b763025ba76540df # Version: Commits on Mar 06, 2025
-------------------------------------------------------------------------------------
Fix deprecation version checks on class fields/pointers,

-----------------------------------------------------------------------------------
tr1x.mk c5757957b9fd23658121acf4837f68ad5a165fe5 # Version: Commits on Mar 06, 2025
-----------------------------------------------------------------------------------
lara/cheat: prevent fly cheat after exploding death

This prevents the fly cheat from being used after the explosion cheat.

Resolves #2584.,

-----------------------------------------------------------------------------------
tr2x.mk c5757957b9fd23658121acf4837f68ad5a165fe5 # Version: Commits on Mar 06, 2025
-----------------------------------------------------------------------------------
lara/cheat: prevent fly cheat after exploding death

This prevents the fly cheat from being used after the explosion cheat.

Resolves #2584.,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk b2d82398298f6a1f89526af8bc2c73909fa2b658 # Version: Commits on Mar 06, 2025
------------------------------------------------------------------------------------------
engine: common: net_http: fix decompression for compressed but not chunked files,

-----------------------------------------------------------------------------------------------
libretro-bennugd.mk 3b1cce4bc787b1c6bec2b270bf3a7a595479c5bb # Version: Commits on Mar 05, 2025
-----------------------------------------------------------------------------------------------
switch to zig 0.14.0 release,

---------------------------------------------------------------------------------------------
libretro-fbneo.mk af263691a6c6985299b293e15e84105b713a726d # Version: Commits on Mar 06, 2025
---------------------------------------------------------------------------------------------
(libretro) update files,

-----------------------------------------------------------------------------------------------
libretro-flycast.mk 562f78cd71bdd3687b4054d3782f3df523d5aff9 # Version: Commits on Mar 05, 2025
-----------------------------------------------------------------------------------------------
libretro: build osx-x64 build on new builder,

------------------------------------------------------------------------------------------------
libretro-freeintv.mk 6efc4b8fd4c7423ec1f5ff1913b854529135b565 # Version: Commits on Mar 05, 2025
------------------------------------------------------------------------------------------------
Add support for V2 Core Options and add option to set default controller. (#79)

* Update libretro-common

* Update libretro-common

* Enable Core Options V2 support, and set a core option to set the default controller as Left or Right.,

-----------------------------------------------------------------------------------------------------
libretro-mame2003-plus.mk f40e11ed06a99f610cda15e4be88d5512f0bfdc1 # Version: Commits on Mar 05, 2025
-----------------------------------------------------------------------------------------------------
Extreme Downhill fix crash at the end of the game,

------------------------------------------------------------------------------------------------
libretro-panda3ds.mk 96e1c8fcd3ea02dc480546cf03e6ed7be21e021e # Version: Commits on Mar 06, 2025
------------------------------------------------------------------------------------------------
AppDataDocumentProvider: Typo (#740),

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk 02734b03a1cde31f02fc4f6c1591da39a9a39881 # Version: Commits on Mar 06, 2025
----------------------------------------------------------------------------------------------
Merge pull request #20080 from hrydgard/framedump-issues

Fix some framedump playback issues,

---------------------------------------------------------------------------------------------
libretro-vba-m.mk 6178526cd96d29d89185a26d873e5a6339ddfb67 # Version: Commits on Mar 06, 2025
---------------------------------------------------------------------------------------------
translations: transifex pull

Signed-off-by: Rafael Kitover <rkitover@gmail.com>,