Revert "package/x265: bump version to 2.1"
This reverts commit 560fe5f69c658547f68577ca983615377fb72775.

Adding -DCROSS_COMPILE_ARM=ON to _CONF_OPTS will not fix the build:

/home/buildroot/br2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gnu/stubs.h:7:29:
  fatal error: gnu/stubs-soft.h: No such file or directory

because cross-compiling x265 is only supported for soft-float abi:
https://bitbucket.org/multicoreware/x265/src/583fc74fc0a29f330187dbd78151c30a3e03d5a7/source/CMakeLists.txt?at=default#CMakeLists.txt-211

Fixes
http://autobuild.buildroot.net/results/6ec/6ec75cc176e05bfc6287dc54fa1a53e0ffc0521d/

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>