package/softether: fix compilation error due to librt linking
/home/buildroot/instance-0/output/build/host-softether-16b713b98da8dba29f0f845d5a8c36d6f7c34824/src/Mayaqua/Unix.c:2066:
undefined reference to `clock_gettime'

[Thomas: remove commit d2cd96eb6864b29337a9bb92db36c99ff7b1290e, which
was a different fix for the same problem.]

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>