glmark2: depend on host-python
The waf build system of glmark2 needs Python 2 as stated on its README
file:

python 2.x (>= 2.4) for the build system (waf)

Building it with a system with Python 3 as the default Python version
will result on a failure like this one:

File "waflib/Utils.py", line 199
    except OSError ,e:
                   ^
SyntaxError: invalid syntax

So, in order to fix this, make this package depending on host-python and
also run the waf script using $(HOST_DIR)/usr/bin/python2.

At the same time delete 3 Python environment variables passed to the waf
script during the configure phase which it seems there aren't needed for
anything.

Fixes:

  http://autobuild.buildroot.net/results/fc6/fc6cd2a90bbb0e6f80f6c4afaae1430f82e54046/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>