configs/olimex_a33_olinuxino: U-Boot needs pylibfdt
The U-Boot configuration for the olimex_a33_olinuxino needs pylibfdt,
and therefore needs host-swig. Without this, the build fails with:

  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  scripts/dtc/pylibfdt/Makefile:27: recipe for target 'scripts/dtc/pylibfdt/_libfdt.so' failed

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/269139202

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>