Updates on Apr 16, 2026 20:10
-------------------------------------------------------------------------------------
azahar.mk d4b5633cf0212ad8d347e012e10b4d5ef0bcd3f1 # Version: Commits on Apr 16, 2026
-------------------------------------------------------------------------------------
qt Fix compilation issues in status LED code (#2045)

solves a build issue a ***lot*** of [L4T Megascript](https://github.com/cobalt2727/L4T-Megascript) users were reporting to me on Linux. C++ is definitely not my strong suit, but per https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/pow-powf-powl?view=msvc-170#remarks `pow` has identical behavior in C++ projects. no clue why `powf` worked fine on your environment when developing this but not other people's.

```cmake

[ 98%] Building CXX object src/citra_qt/CMakeFiles/citra_qt.dir/qt_image_interface.cpp.o

/home/runner/azahar/src/citra_qt/notification_led.cpp:56:15: error: no member named 'powf' in namespace 'std'; did you mean simply 'powf'?

   56 |     float t = std::powf(pwm, 1.f / gamma);

      |               ^~~~~~~~~

      |               powf

/usr/include/aarch64-linux-gnu/bits/mathcalls.h:140:1: note: 'powf' declared here

  140 | __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));

      | ^

/usr/include/math.h:280:3: note: expanded from macro '__MATHCALL_VEC'

  280 |   __MATHCALL (function, suffix, args)

      |   ^

/usr/include/math.h:287:3: note: expanded from macro '__MATHCALL'

  287 |   __MATHDECL (_Mdouble_,function,suffix, args)

      |   ^

/usr/include/math.h:289:3: note: expanded from macro '__MATHDECL'

  289 |   __MATHDECL_1(type, function,suffix, args); \\

      |   ^

note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)

/usr/include/math.h:297:15: note: expanded from macro '__MATHDECL_1_IMPL'

  297 |   extern type __MATH_PRECNAME(function,suffix) args __THROW

      |               ^

/usr/include/math.h:326:34: note: expanded from macro '__MATH_PRECNAME'

  326 | # define __MATH_PRECNAME(name,r) name##f##r

      |                                  ^

<scratch space>:97:1: note: expanded from here

   97 | powf

      | ^

1 error generated.

make[2]: *** [src/citra_qt/CMakeFiles/citra_qt.dir/build.make:1573: src/citra_qt/CMakeFiles/citra_qt.dir/notification_led.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

make[1]: *** [CMakeFiles/Makefile2:3481: src/citra_qt/CMakeFiles/citra_qt.dir/all] Error 2

make: *** [Makefile:166: all] Error 2

```,

-----------------------------------------------------------------------------------
cemu.mk 553990a25ee7a9e6e9b11d13a52f0448e78e116e # Version: Commits on Apr 16, 2026
-----------------------------------------------------------------------------------
debugger: fix crash when adding breakpoint

Checking the item in the event handler that is triggered when an option is checked caused recursion stack overflow

fixes: #1876,

------------------------------------------------------------------------------------------
dolphin-emu.mk 8f638bfee55e1b63069e2f6037a451b063d0d359 # Version: Commits on Apr 16, 2026
------------------------------------------------------------------------------------------
Merge pull request #14585 from jordan-woyak/gamesettings-shrek-lines

GameSettings: Enable VertexRounding in \Shrek Smash n' Crash Racing\.,

--------------------------------------------------------------------------------------
melonds.mk 0a65c3785f88c3d3f057e9cee3145ce103a3382b # Version: Commits on Apr 16, 2026
--------------------------------------------------------------------------------------
add RTC sync option (fixes #2589)

also allow to change date/time while game is running,

----------------------------------------------------
pcsx2.mk v2.7.263 # Version: Commits on Apr 15, 2026
----------------------------------------------------
- [GS/GL/DX11: Don't bind source tex on shader resource if it's tex is fb with no barrier.](https://github.com/PCSX2/pcsx2/pull/14253)

-------------------------------------------------------------------------------------
ppsspp.mk 0f7300b45326d644294de460f40d2b0e1b90c0c8 # Version: Commits on Apr 16, 2026
-------------------------------------------------------------------------------------
Merge pull request #21564 from hrydgard/xml-support

Adhoc: status.xml support,

------------------------------------------------------------------------------------
rpcs3.mk a7c606c8ac8951760868fd3dce2e694631c7bb4f # Version: Commits on Apr 15, 2026
------------------------------------------------------------------------------------
sys_fs: Add unit tests,

---------------------------------------------------------------------------------------
touchhle.mk e35f26686b12b79d8d50966b8216f0db798ac012 # Version: Commits on Feb 12, 2025
---------------------------------------------------------------------------------------
div() implementation

Change-Id: I4ead8d28f3ac96bc91a74fbb0ea859aa4901685a,

-------------------------------------------------
vice.mk r46076 # Version: Commits on Apr 16, 2026
-------------------------------------------------
null

-----------------------------------------------------------------------------------
ymir.mk 404197d4c817fe88e75a5f66f66c341624ef7e49 # Version: Commits on Apr 16, 2026
-----------------------------------------------------------------------------------
fix(VDP2): Illegal scroll CP accesses cause a shift if there aren't enough valid accesses in other banks and the illegal accesses occurs in the same bank as the PN access

Fixes fog background shift in Sonic 3D Blast,

-------------------------------------------------------------------------------------
ikemen.mk cad257e93ef4b0ec75826fc9682d60c3720077e2 # Version: Commits on Apr 16, 2026
-------------------------------------------------------------------------------------
Merge pull request #3511 from Alceris/ignorereversaldef

refactor: Rename MissOnReversalDef to IgnoreReversalDef,

----------------------------------------------------------------------------------------------------
gamenetworkingsockets.mk 35d7b8019256008570b961a3291a846f155e995f # Version: Commits on Apr 16, 2026
----------------------------------------------------------------------------------------------------
Fix support for reading TOS field on OSX.

This fixes #359 and #376,

----------------------------------------------------
ngtcp2.mk v1.22.1 # Version: Commits on Apr 16, 2026
----------------------------------------------------
Bump package and library versions,

------------------------------------------------------------------------------------------
fallout2-ce.mk 8f3ccca71b2ed44f3f5d0227b8b1e5eb683ac007 # Version: Commits on Apr 16, 2026
------------------------------------------------------------------------------------------
Implement several trivial opcodes (#380)

* Implement several trivial opcodes

* get/set_combat_free_move

* item_weight

* obj_is_openable

* get/set_critter_current_ap,

---------------------------------------------------
nblood.mk r14336 # Version: Commits on Apr 16, 2026
---------------------------------------------------
,

--------------------------------------------------------------------------------------
omf2097.mk 015e0bbbf08ae7026e2fc1fb31529503a6755a3e # Version: Commits on Apr 15, 2026
--------------------------------------------------------------------------------------
Merge pull request #1379 from omf2097/support-opus-loop-tags

opus: Support OGG LOOPSTART/LOOPEND/LOOPLENGTH tags.,

----------------------------------------------------------------------------------------
openjkdf2.mk 4fb33b7f81baffd77d63ad59887b543d6f42e6f3 # Version: Commits on Apr 16, 2026
----------------------------------------------------------------------------------------
Merge pull request #436 from bobberb/fix/glx-visual-steamdeck

Remove forward-compatible GL flag on Linux to fix Steam Deck GLX error,

---------------------------------------------------------------------------------------
mangohud.mk 6dfe3dc9aca64df5e0008caf679509d2902f512f # Version: Commits on Apr 03, 2026
---------------------------------------------------------------------------------------
Invert condition for GPU power usage check

Introduced by commit b058618,

----------------------------------------------------------------------------------------
retroarch.mk 02af9afb5dbb0ff36dc113c2ceb2adfa6773a0ba # Version: Commits on Apr 16, 2026
----------------------------------------------------------------------------------------
GFX: Remove unused video_driver_get_flags and wrapper

video_context_driver_get_flags() now merges flags from both

the poke interface and the context driver (commit be2d747).

This made two functions redundant:

  - video_driver_get_flags (static) â€” checked poke only

  - video_driver_get_flags_wrapper â€” checked poke then context

Both are subsets of what video_context_driver_get_flags() now

does.  Remove them and simplify video_driver_test_all_flags()

to a single video_context_driver_get_flags() call.,

---------------------------------------------------------------------------------------
vpinball.mk 5c3aca0ee7502a25d7b6034150fbd25d0154bc2c # Version: Commits on Apr 16, 2026
---------------------------------------------------------------------------------------
plugins: add some additional logs to serum (for authors),

-----------------------------------------------------------------------------------
qrtr.mk ae881086dfd29f828dcadb56e4b32a09fdc5c202 # Version: Commits on Apr 16, 2026
-----------------------------------------------------------------------------------
Merge pull request #40 from z3ntu/libqrtr-static

lib: meson.build: Don't force shared libqrtr,

----------------------------------------------------------------------------------------
doomretro.mk 4f1887b24dc12319d639fc7038ebe6c0e5feceb1 # Version: Commits on Apr 16, 2026
----------------------------------------------------------------------------------------
Fix translucency of some sprites in BTSX,

--------------------------------------------------------------------------------------
yquake2.mk 6ef01d9781def344a9ceff696ffbd19022bbd584 # Version: Commits on Apr 14, 2026
--------------------------------------------------------------------------------------
game: add level.is_n64

Based on:

* https://github.com/Paril/q2pro.git,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk 62201900cff737c275494aaf650aa0ee73b11fe1 # Version: Commits on Apr 16, 2026
------------------------------------------------------------------------------------------
ref: null: remove unused function,

---------------------------------------------------------------------------------------------
libretro-citra.mk d4b5633cf0212ad8d347e012e10b4d5ef0bcd3f1 # Version: Commits on Apr 16, 2026
---------------------------------------------------------------------------------------------
qt Fix compilation issues in status LED code (#2045)

solves a build issue a ***lot*** of [L4T Megascript](https://github.com/cobalt2727/L4T-Megascript) users were reporting to me on Linux. C++ is definitely not my strong suit, but per https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/pow-powf-powl?view=msvc-170#remarks `pow` has identical behavior in C++ projects. no clue why `powf` worked fine on your environment when developing this but not other people's.

```cmake

[ 98%] Building CXX object src/citra_qt/CMakeFiles/citra_qt.dir/qt_image_interface.cpp.o

/home/runner/azahar/src/citra_qt/notification_led.cpp:56:15: error: no member named 'powf' in namespace 'std'; did you mean simply 'powf'?

   56 |     float t = std::powf(pwm, 1.f / gamma);

      |               ^~~~~~~~~

      |               powf

/usr/include/aarch64-linux-gnu/bits/mathcalls.h:140:1: note: 'powf' declared here

  140 | __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));

      | ^

/usr/include/math.h:280:3: note: expanded from macro '__MATHCALL_VEC'

  280 |   __MATHCALL (function, suffix, args)

      |   ^

/usr/include/math.h:287:3: note: expanded from macro '__MATHCALL'

  287 |   __MATHDECL (_Mdouble_,function,suffix, args)

      |   ^

/usr/include/math.h:289:3: note: expanded from macro '__MATHDECL'

  289 |   __MATHDECL_1(type, function,suffix, args); \\

      |   ^

note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)

/usr/include/math.h:297:15: note: expanded from macro '__MATHDECL_1_IMPL'

  297 |   extern type __MATH_PRECNAME(function,suffix) args __THROW

      |               ^

/usr/include/math.h:326:34: note: expanded from macro '__MATH_PRECNAME'

  326 | # define __MATH_PRECNAME(name,r) name##f##r

      |                                  ^

<scratch space>:97:1: note: expanded from here

   97 | powf

      | ^

1 error generated.

make[2]: *** [src/citra_qt/CMakeFiles/citra_qt.dir/build.make:1573: src/citra_qt/CMakeFiles/citra_qt.dir/notification_led.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

make[1]: *** [CMakeFiles/Makefile2:3481: src/citra_qt/CMakeFiles/citra_qt.dir/all] Error 2

make: *** [Makefile:166: all] Error 2

```,

---------------------------------------------------------------------------------------------------
libretro-dosbox-pure.mk 93cf48bb22b30a9bc657511658cf4dbcd9a727eb # Version: Commits on Apr 16, 2026
---------------------------------------------------------------------------------------------------
Add volume settings for the various DOS devices (Sound Blaster, Adlib, MIDI, etc.),

---------------------------------------------------------------------------------------------
libretro-fbneo.mk aad260ac2c5c9dd94d01ffefaddf2c371a37f61a # Version: Commits on Apr 16, 2026
---------------------------------------------------------------------------------------------
(libretro) update files,

-----------------------------------------------------------------------------------------------
libretro-geolith.mk 23d10b5d3add68d14b958c10cd0a6cb65652db91 # Version: Commits on Apr 16, 2026
-----------------------------------------------------------------------------------------------
geo_cd: Fix CDDA playback for Front/Top Loader,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk 0f7300b45326d644294de460f40d2b0e1b90c0c8 # Version: Commits on Apr 16, 2026
----------------------------------------------------------------------------------------------
Merge pull request #21564 from hrydgard/xml-support

Adhoc: status.xml support,

----------------------------------------------------------------------------------------------
libretro-stella.mk 4483eb7539d02125b58dfc164963d78c7efd003f # Version: Commits on Apr 15, 2026
----------------------------------------------------------------------------------------------
Potential speedup to Settings class, but using unordered_map instead of map.,

-----------------------------------------------------------------------------------------------------
libretro-virtualjaguar.mk dd44259f8dca0ba87068eb2264367c01e131c263 # Version: Commits on Apr 16, 2026
-----------------------------------------------------------------------------------------------------
Merge pull request #101 from Provenance-Emu/libretro/feature/simd-blitter

SIMD-accelerated blitter operations (SSE2, NEON),