Updates on Nov 11, 2024 19:24
---------------------------------------------------------------------------------------
applewin.mk a100f0b7451dc91dcb685437a4b299134c034da7 # Version: Commits on Nov 10, 2024
---------------------------------------------------------------------------------------
Merge pull request #190 from AppleWin/master

Add cmd line option (for testing): -load-state-ignore-hdc-fw,

-----------------------------------------------------------------------------------
cemu.mk ca2e0a7c31dcaeac110dc4aa703a992b55c8155f # Version: Commits on Nov 11, 2024
-----------------------------------------------------------------------------------
nsyshid: Add support for emulated Dimensions Toypad (#1371),

------------------------------------------------------------------------------------------
dolphin-emu.mk 80ea68b13c06ae3fa57775de39c902ed9c3c8e84 # Version: Commits on Nov 11, 2024
------------------------------------------------------------------------------------------
Merge pull request #13183 from Tilka/sync_on_fifo_reset

ProcessorInterface: sync GPU just before PI_FIFO_RESET,

------------------------------------------------------------------------------------------
duckstation.mk e69f0d3cce25618942dd6e40a36b0f3f60a330b2 # Version: Commits on Nov 11, 2024
------------------------------------------------------------------------------------------
OpenGLDevice: Support both XCB and Xlib

Required for NVIDIA+XWayland.,

-------------------------------------------------------------------------------------
ikemen.mk d78eb17447998a3ef864689ee67d7ddac26c97ae # Version: Commits on Nov 11, 2024
-------------------------------------------------------------------------------------
refactor: merge correction,

-----------------------------------------------------------------------------------------
lightspark.mk 4ddeeb52c40e0e48693b9b1c71d1ae4e83b6f945 # Version: Commits on Nov 10, 2024
-----------------------------------------------------------------------------------------
move all parsed swf stuff into its applicationDomain

this makes garbage collection for loaded swf movies possible

(while keeping the classes and tags)

this also includes several smaller changes:

- rework mask handling so that a DisplayObject can be the mask of

multiple other DisplayObjects

- improved detection of cyclic references in garbage collection

- fixed reference counting in Loader/LoaderInfo combination

- fixed reference counting when adding a child that was already added to

the same DisplayObjectContainer

- properly finish job threads in URLLoader

- better detection of invalid pointers in asAtoms,

--------------------------------------------------------------------------------------
melonds.mk 7c1d2a64f4afe6b02a93c3342a91fc932015742e # Version: Commits on Nov 11, 2024
--------------------------------------------------------------------------------------
Set WIN32_LEAN_AND_MEAN, gets rid of the winsock2 warnings and probably

speeds up compilation a tiny bit

oh and NOMINMAX too for good measure while we're at it,

---------------------------------------------------
pcsx2.mk v2.3.11 # Version: Commits on Nov 11, 2024
---------------------------------------------------
- [GameDB: NBA 2K6 fix hangs on PAL version](https://github.com/PCSX2/pcsx2/pull/11995)

,

-------------------------------------------------------------------------------------
ppsspp.mk d3aa19ebad0b423498a5b651780de4bfe0a43e21 # Version: Commits on Nov 11, 2024
-------------------------------------------------------------------------------------
Merge pull request #19624 from hrydgard/disable-debugger

Disable debuggers when the RetroAchievements hardcore mode is enabled,

----------------------------------------------------
ryujinx.mk 1.2.27 # Version: Commits on Nov 11, 2024
----------------------------------------------------
**Full Changelog**: https://github.com/GreemDev/Ryujinx/compare/Canary-1.2.24...Canary-1.2.27

-----------------------------------------------------------------------------------
xemu.mk 21abcb4520e07e95f831f82cf536dfa247a438b3 # Version: Commits on Nov 11, 2024
-----------------------------------------------------------------------------------
nv2a/vk: Add command buffer region debug markers,

----------------------------------------------------------------------------------------------
ffmpeg-rockchip.mk 841da94b133ae0ded24bf4ae72f08d1cb32d7bcd # Version: Commits on Nov 11, 2024
----------------------------------------------------------------------------------------------
fixup! lavc/rkmppenc: add RKMPP H264 and HEVC encoder

switch from ff_alloc_packet() to ff_get_encode_buffer().

Signed-off-by: nyanmisaka <nst799610810@gmail.com>,

------------------------------------------------------------------------------------
box64.mk b02942c0b0d8491c2d28128c4c948710f47f94f9 # Version: Commits on Nov 11, 2024
------------------------------------------------------------------------------------
[RV64_DYNAREC] Made eflags emulation branchless with xtheadcondmov (#2019)

* [RV64_DYNAREC] Made eflags emulation branchless with xtheadcondmov

* more,

---------------------------------------------------------------------------------------
corsixth.mk 47546ac614bd7fdd8ea821a258bcd99ca8d4ff28 # Version: Commits on Nov 10, 2024
---------------------------------------------------------------------------------------
Merge pull request #2717 from lewri/update-french-cheats

Shorten French cheat strings,

------------------------------------------------------------------------------------------
devilutionx.mk 553d13572667d67732465afde53eb33e546b2851 # Version: Commits on Nov 11, 2024
------------------------------------------------------------------------------------------
CMake: FetchContent `EXCLUDE_FROM_ALL` fixes

On CMake v3.28+, `EXCLUDE_FROM_ALL` is supported natively as an argument

to `FetchContent_Declare`.

On CMake v3.30+, `FetchContent_Populate`, which we use to polyfill

`EXCLUDE_FROM_ALL` support for older versions of CMake, is deprecated

and triggers a noisy warning.

Avoids the warning by using the native `EXCLUDE_FROM_ALL` support on

CMake v3.28+.,

---------------------------------------------------------------------------------------
etlegacy.mk eb5b8282f469935c2077a6b70c861f04f272c7dd # Version: Commits on Nov 11, 2024
---------------------------------------------------------------------------------------
Incrementing version number to 2.83.0,

---------------------------------------------------
nblood.mk r14124 # Version: Commits on Nov 11, 2024
---------------------------------------------------
-

-----------------------------------------------------------------------------------
re2c.mk c4e779cab5596ff326acbecac33fea9bd5b4a184 # Version: Commits on Nov 10, 2024
-----------------------------------------------------------------------------------
*.ypp: use api.prefix in all bison-generated parsers

Mostly a cospetic change. I hope to get to the state when `re2c` can be

built with `-flto -Werror=odr`. Right now it fails as:

    src/parse/parser.cc:121:6: error: type 'yysymbol_kind_t' violates the C++ One Definition Rule [-Werror=odr]

This change does not fix it, but at least it clearly solits the exposed

API namespace:

    https://www.gnu.org/software/bison/manual/html_node/Multiple-Parsers.html,

----------------------------------------------------------------------------------------
retroarch.mk bb808dfc699eac406fb98ff4d1efab5fe844e05d # Version: Commits on Nov 11, 2024
----------------------------------------------------------------------------------------
Fetch translations from Crowdin,

-----------------------------------------------
dxvk.mk v2.5 # Version: Commits on Nov 11, 2024
-----------------------------------------------
## Memory managment

Resource and memory management were completely rewritten in order to use allocated video memory more efficiently:

- Reduced fragmentation may reduce peak memory usage in games such as **God of War** by up to 1 GiB in extreme cases.

- Memory defragmentation is now performed periodically to return some unused memory back to the system.

  The goal is **not** to reduce VRAM usage at all costs; instead this is done conservatively if the system is under memory pressure, or if a significant amount of allocated memory is unused. Keeping *some* unused memory is useful to quickly service subsequent allocations.

**Note:** Defragmentation is currently disabled on Intel's ANV driver, see #4434. The `dxvk.enableMemoryDefrag` config option can be set to enable or disable this feature via the the [Configuration file](https://github.com/doitsujin/dxvk/wiki/Configuration).

### Driver support

While technically not required, the new memory management works best on drivers that support both `VK_EXT_memory_budget` and `VK_KHR_maintenance5`. The [Driver Support](https://github.com/doitsujin/dxvk/wiki/Driver-support) page was updated accordingly.

## D3D8 / D3D9

### Software cursor

Support for emulated cursors was implemented for the D3D9 cursor API, which allows games to set an arbitrary image as the mouse cursor. This fixes an issue in **Dungeon Siege 2** (#3020) and makes the cursor appear correctly in **Act of War** and various older D3D8 games. (PR #4302)

![Bildschirmfoto-693](https://github.com/user-attachments/assets/f46d576d-f70f-4369-83cb-c2f2831b9b3e)

### Sampler pool

Unreal Engine 3 games using D3D9 have a quirk in that they pass a seemingly uninitialized value as the mipmap LOD bias. In order to avoid creating more Vulkan sampler objects than the driver supports, previous versions of DXVK would round the LOD bias to a multiple of 0.5, which could introduce visual inaccuracies. As a more correct soluition, DXVK will now destroy unused Vulkan samplers on the fly and use the correct LOD bias.

**Note:** The aforementioned workaround was never needed or used in the D3D11 implementation, it only affected D3D9.

### Bug fixes and Improvements

- On Nvidia driver version **565.57.01** and newer, strict float emulation is enabled by default for improved correctness.

  Games for which this option was already enabled may see a small performance uplift on this driver.

- Made various changes to potentially improve performace on certain mobile GPUs. (includes PR #4358)

- Display modes are now ordered by refresh rate to be more consistent with wined3d and fix issues with some games picking the wrong display mode.

- Fixed a large number of wine test failures.

- **Ascension to the Throne**: Fixed old regression that would cause parts of the ground to render black. (#4338, PR #4341)

- **Command & Conquer: Generals**: Fixed performance issue caused by a missing D3D8 entry point. (PR #4342)

- **King's Bounty: Warriors of the North**: Fixed water rendering issue. (#4344, PR #4350)

- **Tomb Raider: Legend**: Fixed flickering geometry with strict float emulation. (#4319, PR #4442)

- **Rayman 3**: Fixed a regression that caused rendering issues. (#4422, PR #4423)

## D3D11 / DXGI

### Resource management changes

In order to reduce system memory pressure and improve stability in 32-bit games, creating, uploading and discarding resources is now throttled if the amount of temporary staging memory allocations exceed a certain threshold. This fixes crashes in **Total War: Rome II** and a number of other games. Additionally, large `DYNAMIC` textures commonly used for video playback will no longer use a staging buffer.

The `d3d11.maxDynamicImageBufferSize` and `d3d11.maxImplicitDiscardSize` options were removed accordingly; affected games such as **Total War: Warhammer III** and **Ryse: Son of Rome** should now perform well by default, without excessive memory usage.

**Note:** These changes negatively affect CPU-bound performance in a number of games, including **Shadow Warrior 2**.

### Bug fixes and Improvements

- `SEQUENTIAL` swap effects are now implemented for DXGI swap chains, which allows games to read previously presented backbuffers. This fixes an issue wherein savegame thumbnails would appear black in certain visual novels. (https://github.com/ValveSoftware/Proton/issues/7017)

- Devirtualized some D3D11 method calls to improve compatibility with Special K.

- Fixed incorrect shader code generation for `EvaluateAttributeSnapped`.

- Lock contention is reduced in certain games that use Deferred Contexts for rendering.

  This may improve performance on older CPUs in **Sekiro: Shadows Die Twice** and some other games.

- **Call of Duty: Modern Warfare 2 Campaign Remastered**: Fixed a possible GPU hang. (#3884)

- **Diablo 4**: Work around an issue where the game does not start if an integrated GPU is exposed.

- **The Sims 4**: Work around a use-after-free bug in the game's D3D11 renderer for real this time. (#4360)

- **Vindictus**: Work around potential rendering issues caused by uninitialized constant buffer data. (#4405, #4406)

- **Yakuza 0** and **Yakuza Kiwami**: Fixed a regression introduced in DXVK 2.4.1 that would cause these games to lock up on start. (PR #4297)

## Miscellaneous changes

- An SDL3 backend was added for dxvk-native. (PR #4326, #4404)

- Fixed an issue introduced in DXVK 2.4.1 which would lead to error messages about failed buffer creation.

- Fixed a long-standing issue where overlapping occlusion queries would lead to incorrect Vulkan usage. (#2698)

- Fixed a rare issue wherein timestamp queries would not be tracked correctly and could read incorrect data.

- Fixed various other issues that led to Vulkan validation errors in games such as **Dishonored 2**, **Tales of Arise** and **The Sims 4**.

- Fixed various issues with MSVC builds. (PR #4444)

- Disabled a workaround for boken render target clears on Nvidia drivers prior to version **560.28.03** on unaffected drivers.

- If supported, `VK_EXT_pageable_device_local_memory` is now used to enable better driver-side memory management.,

----------------------------------------------------------------------------------------
doomretro.mk e53468c42527d930a02866fb1173132c7fe62b5c # Version: Commits on Nov 11, 2024
----------------------------------------------------------------------------------------
Fix line count when parsing `DEHACKED` lumps/files,

-------------------------------------------------------------------------------------
gzdoom.mk a145eac056233caaeeb702f2a15eabdcb6b40dd9 # Version: Commits on Nov 11, 2024
-------------------------------------------------------------------------------------
added constants for the most recently added level flags,

--------------------------------------------------------------------------------------
vkquake.mk fa26828b55896e22c9e8c1076abc7662145fad48 # Version: Commits on Nov 11, 2024
--------------------------------------------------------------------------------------
Fix printf error=format,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk 8a2a7d1180e99e956f37037df331634e3161fe4c # Version: Commits on Nov 11, 2024
------------------------------------------------------------------------------------------
engine: rework how HTTP finite-machine works, use function pointers instead of enum. Preliminary chunked transfer and compression support. (#1862),

---------------------------------------------------------------------------------------------
libretro-fbneo.mk d3b3a962cdb17884153182125dd2689522059f00 # Version: Commits on Nov 11, 2024
---------------------------------------------------------------------------------------------
(libretro) maybe like this,

-----------------------------------------------------------------------------------------------------
libretro-mame2003-plus.mk c86232158c7ccdf0152ff1b42dc160841d37ea6c # Version: Commits on Nov 11, 2024
-----------------------------------------------------------------------------------------------------
Fix scross engine sounds missing - dink,

------------------------------------------------------------------------------------------------
libretro-panda3ds.mk a8d3fb08357c5fa2276ad5079d201605a0ce853b # Version: Commits on Nov 11, 2024
------------------------------------------------------------------------------------------------
Merge pull request #633 from warmenhoven/warmenhoven/pr/lr-mtl

libretro: disable metal rendering backend,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk d3aa19ebad0b423498a5b651780de4bfe0a43e21 # Version: Commits on Nov 11, 2024
----------------------------------------------------------------------------------------------
Merge pull request #19624 from hrydgard/disable-debugger

Disable debuggers when the RetroAchievements hardcore mode is enabled,

----------------------------------------------------------------------------------------------
libretro-stella.mk 2c5882edffc4ccfcc9f969e1212c49177aad93e6 # Version: Commits on Nov 10, 2024
----------------------------------------------------------------------------------------------
Debian build requires libgtest-dev, but is not specified (#1049)

Co-authored-by: Sven Oliver Moll <svolli@svolli.de>,

---------------------------------------------------------------------------------------------
libretro-tic80.mk e3c3bc68fc260e8f2ee431a4c031d2c89ebe27c8 # Version: Commits on Nov 11, 2024
---------------------------------------------------------------------------------------------
fix bpp2 (#2715),