Revert "gnutls: make it non-wchar friendly"
This reverts commit ca317d0ed82ebd7c517f504963b090607c69b8f9

While the fix makes gnutls build without wchar, it doesn't actually work as
there's no rpl_wctomb implementation so the .so ends up with an undefined
reference to wctomb:

./host/usr/bin/arm-linux-nm -D staging/usr/lib/libgnutls.so.28|grep wctomb
         U wctomb

Causing linker errors for packages trying to use it:

  CCLD   msmtp
host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libgnutls.so:
undefined reference to `wctomb'
collect2: ld returned 1 exit status

Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>