kobs-ng: test kernel version for redefines
kobs-ng failed to build with 2.6.36, because enum tested with #ifndef

mtd.c: In function 'mtd_open':
mtd.c:696:42: error: 'MTD_FILE_MODE_NORMAL' undeclared (first use in this
function)
mtd.c:696:42: note: each undeclared identifier is reported only once for each
function it appears in
mtd.c: In function 'mtd_set_ecc_mode':
mtd.c:896:43: error: 'MTD_FILE_MODE_NORMAL' undeclared (first use in this
function)
mtd.c:914:43: error: 'MTD_FILE_MODE_RAW' undeclared (first use in this
function)

Do kernel version test before enum redefines.

Signed-off-by: Sergey Alyoshin <alyoshin.s@gmail.com>
Tested-by: Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>