wavpack: fetch upstream patch to remove wchar dependency
The recent bump to version 5.1.0 added a dependency on wchar:

```
import_id3.c:37:34: error: unknown type name 'wchar_t'
```

This issue has been reported upstream [1] and a fix was commited by
upstream to remove the wchar dependency [2].

Fixes:
http://autobuild.buildroot.net/results/9a6/9a693f5b798571917f36cfb7661e2f2638aac550/
http://autobuild.buildroot.net/results/44c/44c8227043045baf4f043da44b8129e43dfff687/
http://autobuild.buildroot.net/results/a80/a80221dcc0860046ebdf0bbf454e056b1e20df83/
.. and more.

The build was successfully tested with the 'br-arm-basic-2017.02-rc1-2-g133c5ac'
toolchain.

[1] https://github.com/dbry/WavPack/issues/19
[2] https://github.com/dbry/WavPack/commit/876fc3f3907e871d0938ac6c8c5252f5f31abd1f

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>