package/boost: bump to version 1.58.0
Add patch to fix build issues for mips and sh targets:
error: unrecognized command line option '-m32'

Fixes:
http://autobuild.buildroot.org/results/66c/66c3a868816dfe4bd4d0ffafec6988fd87a2c058/
http://autobuild.buildroot.net/results/ccd/ccd5c83963032ba49b1627b1dff39e34a9486943/

Patch send upstream:
https://github.com/boostorg/build/pull/76

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Tested-by: Gergely Imreh <imrehg@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>