Updates on May 24, 2024 17:03
----------------------------------------------------------------------------------------
retroarch.mk 5db932d366c8d2ce8bd8e132e4931c4a9e30ffed # Version: Commits on May 24, 2024
----------------------------------------------------------------------------------------
gfx_widgets_draw_task_msg - get rid of one strlen,

--------------------------------------------------------------------------------------------------
libretro-beetle-psx.mk f7d733b935be185da633be660c73d8f91d6c6883 # Version: Commits on May 24, 2024
--------------------------------------------------------------------------------------------------
Fetch translations & Recreate libretro_core_options_intl.h,

---------------------------------------------------------------------------------------------
libretro-bsnes.mk 593cc3b63f5685a5723fc0a955f7d6abccf7c910 # Version: Commits on May 24, 2024
---------------------------------------------------------------------------------------------
Fetch translations & Recreate libretro_core_options_intl.h,

----------------------------------------------------------------------------------------------
libretro-fceumm.mk 6f6b527b9d006c4b5460d2e41fea4f70470fbb98 # Version: Commits on May 24, 2024
----------------------------------------------------------------------------------------------
Add mapper 265,

-----------------------------------------------------------------------------------------------
libretro-flycast.mk 0a0d30309b004d10066421511586bab750e38e3d # Version: Commits on May 24, 2024
-----------------------------------------------------------------------------------------------
achievements: run all http requests on a background thread

Fixes freeze when unlocking cheevos and other events.

Issue #761,

----------------------------------------------------------------------------------------------
libretro-kronos.mk 66a74d08f4ee4674377ca3ffecfec9744ff9e290 # Version: Commits on May 24, 2024
----------------------------------------------------------------------------------------------
gcc14: fix return mismatch

removed return value on multiplaces to avoid this error:

Compiling ../sys/vdp1/src/vdp1.c.o

../sys/vdp1/src/vdp1.c: In function 'Vdp1DebugCommand':

../sys/vdp1/src/vdp1.c:2108:23: error: 'return' with a value, in function returning void [-Wreturn-mismatch]

 2108 |                return 0;

      |                       ^

../sys/vdp1/src/vdp1.c:1989:6: note: declared here

 1989 | void Vdp1DebugCommand(u32 number, char *outstring)

      |      ^~~~~~~~~~~~~~~~,

-----------------------------------------------------------------------------------------------------
libretro-mame2003-plus.mk fa047061785494298655ffbedddcb89165fed393 # Version: Commits on May 24, 2024
-----------------------------------------------------------------------------------------------------
Selectively hide x way joystick menu item (#1740),

--------------------------------------------------------------------------------------------
libretro-mgba.mk 8c0a28477b23db01c0ce8ec916542097c1aa05f5 # Version: Commits on May 24, 2024
--------------------------------------------------------------------------------------------
GBA SIO: Improve MULTI timing,

--------------------------------------------------------------------------------------------
libretro-pc88.mk 31ccb0c2b634e73355a00086901c0d464846b90a # Version: Commits on May 23, 2024
--------------------------------------------------------------------------------------------
Merge pull request #67 from ToKe79/gcc14_fixes

gcc14 fixes,

----------------------------------------------------------------------------------------------
libretro-ppsspp.mk a04ad1c7f72fc7ed4a04db49c04ebbc8ff262116 # Version: Commits on May 24, 2024
----------------------------------------------------------------------------------------------
Merge pull request #19178 from hrydgard/text-draw-refactor

Text draw refactor part #1,

----------------------------------------------------------------------------------------------
libretro-prboom.mk 9d412db570d3291829b308e6d1ac17f04acdda17 # Version: Commits on May 23, 2024
----------------------------------------------------------------------------------------------
Removed rendering stats,

---------------------------------------------------------------------------------------------------
libretro-swanstation.mk eab1d36201eef8eaed3a3fe1935c81f4b463c2c1 # Version: Commits on May 24, 2024
---------------------------------------------------------------------------------------------------
Use path_is_directory directly,

------------------------------------------------------------------------------------------------
libretro-tyrquake.mk 2f3e7ab1f8907d8ff9e3c43cd1b55c0daa17c74d # Version: Commits on May 24, 2024
------------------------------------------------------------------------------------------------
Cleanups - remove unused code,

---------------------------------------------------------------------------------------------
libretro-wasm4.mk f7b5360d12e07623646006b4f54a96842a37569b # Version: Commits on May 23, 2024
---------------------------------------------------------------------------------------------
Merge pull request #717 from JerwuQu/jwq_rect-bounds

rect: fix bounds,

-------------------------------------------------------------------------------------------
glsl-shaders.mk cbb2e39293475de87d25d5235c02c1db8d02397b # Version: Commits on May 23, 2024
-------------------------------------------------------------------------------------------
Update Glow (crt-consumer, crt-sines) use hardware 9-tap blur using linear accel. (#442)

* update crt-sines glow

use hardware 5-tap, effectively 9-tap blur using linear.

https://www.rastergrid.com/blog/2010/09/efficient-gaussian-blur-with-linear-sampling/

* Update glow_y.glsl

* Update crt-sines.glsl

* Update crt-sines.glslp

* Update crt-consumer.glslp

* Update crt-lottes-mini.glsl

* Update crt-lottes-mini.glslp,

--------------------------------------------------------------------------------------------
slang-shaders.mk 6cb93ce1be67b314a96f5e346befb2b58b63eb04 # Version: Commits on May 23, 2024
--------------------------------------------------------------------------------------------
koko-aio hotfix4 (#597)

* koko-aio hotfix4

* Fix inflation for tate, take 2,

---------------------------------------------------------------------------------------
amiberry.mk 1e081a37285f89ff2dfbf8fc8e93f80f9c5336ad # Version: Commits on May 24, 2024
---------------------------------------------------------------------------------------
feat: Merge latest updates from master

- Merged latest FloppyBridge version

- FloppyBridge is now an external library (plugin)

- Added plugins directory, for external libraries (capsimg.so, libfloppybridge.so)

- Updated Makefile and CMakeLists files

- Other minor updates from preview,

------------------------------------------------------------------------------------------
dolphin-emu.mk 222a3930807545d9ebffebfbd13c3a816f788434 # Version: Commits on May 23, 2024
------------------------------------------------------------------------------------------
Merge pull request #12782 from brad0/openbsd_arm64

Add OpenBSD/arm64 support.,

---------------------------------------------------------------------------------------------
dosbox-staging.mk e806e71f9564c8844c5fe3b01b187a71793b23a4 # Version: Commits on May 24, 2024
---------------------------------------------------------------------------------------------
Update dev build download URL,

------------------------------------------------------------------------------------------
duckstation.mk a7f2ad37de936d68e8881aa6878e91ed213d228a # Version: Commits on May 24, 2024
------------------------------------------------------------------------------------------
InputManager: Fix exit menu button forwarding to game,

--------------------------------------------------------------------------------------
flycast.mk 0a0d30309b004d10066421511586bab750e38e3d # Version: Commits on May 24, 2024
--------------------------------------------------------------------------------------
achievements: run all http requests on a background thread

Fixes freeze when unlocking cheevos and other events.

Issue #761,

-------------------------------------------------------------------------------------
ikemen.mk 6d0c04b2f6eae00ac36c9430968840c02d59f60d # Version: Commits on May 24, 2024
-------------------------------------------------------------------------------------
style: fix code style issues with gofmt,

-------------------------------------------------------------------------------------
ppsspp.mk a04ad1c7f72fc7ed4a04db49c04ebbc8ff262116 # Version: Commits on May 24, 2024
-------------------------------------------------------------------------------------
Merge pull request #19178 from hrydgard/text-draw-refactor

Text draw refactor part #1,

------------------------------------------------------------------------------------
rpcs3.mk 3dfbd14de2856c7c058bf859e77182c514a61084 # Version: Commits on May 24, 2024
------------------------------------------------------------------------------------
SPU LLVM: Implement PUTLLC16 for accurate RSX reservations,

-------------------------------------------------------------------------------------
ruffle.mk 8ac7a58d4e02c3b034ea61a2b9e169bb2b72f62f # Version: Commits on May 24, 2024
-------------------------------------------------------------------------------------
debug_ui: Improve EditText tab

This patch adds multiple properties and controls to EditText tab.

This includes for instance:

* border, border color,

* background, background color,

* editable, selectable, word wrap properties,

* autosize, max chars, restrict, etc.,

------------------------------------------------------
ryujinx.mk 1.1.1321 # Version: Commits on May 24, 2024
------------------------------------------------------
For more information about this release please check out the official [Changelog](https://github.com/Ryujinx/Ryujinx/wiki/Changelog).,

-----------------------------------------------------------------------------------
suyu.mk e880ebdc56d41cbc8706ddc331509e7ef427142a # Version: Commits on May 24, 2024
-----------------------------------------------------------------------------------
Add GitHub Action file,

---------------------------------------------------------------------------------------
alephone.mk d82fab3a6168c604ace8811cfa574464b2467cf2 # Version: Commits on May 24, 2024
---------------------------------------------------------------------------------------
Update vcpkg-configuration.json,

------------------------------------------------------------------------------------
box64.mk fcf0cf00d0a82649ba0cf9f6a8c0450bb6ed5f47 # Version: Commits on May 24, 2024
------------------------------------------------------------------------------------
Added support for XSAVE/XRSTOR ([ARM64_DYNAREC] too),

---------------------------------------------------------------------------------------
fheroes2.mk e6710229fce2092923594baa450bd6ce276bcba5 # Version: Commits on May 24, 2024
---------------------------------------------------------------------------------------
Add missing Sphinx part (#8703),

-------------------------------------------------------------------------------------
nblood.mk c83001589f0bcbf8be04050d9a60839f0f8c4b4a # Version: Commits on May 24, 2024
-------------------------------------------------------------------------------------
Clean up references to removed/replaced libraries,

--------------------------------------------------------------------------------------
stalker.mk 6e3a06938ee2d95a301ff870371951e4d92f4d89 # Version: Commits on May 23, 2024
--------------------------------------------------------------------------------------
UI Focus system WIP (#943),

----------------------------------------------------------------------------------
stk.mk 3d86d937695bd8d1056d14d05bd867ba876a0614 # Version: Commits on May 23, 2024
----------------------------------------------------------------------------------
Use forward enum declaration,

----------------------------------------------------------------------------------------
supertux2.mk b902362b1de62180b61d2f4f625ae1454a76b171 # Version: Commits on May 24, 2024
----------------------------------------------------------------------------------------
Update translations,

----------------------------------------------------------------------------------------
doomretro.mk 7acb4477545264ac0bca3541775e0e7be6b845b4 # Version: Commits on May 24, 2024
----------------------------------------------------------------------------------------
More minor tweaks,

-----------------------------------------------------------------------------------------
sonic3-air.mk ee8d82e6ffdfb5e4616b735610c030c19497eaf2 # Version: Commits on May 24, 2024
-----------------------------------------------------------------------------------------
Minor rework in OpenGLRenderResources and PaletteManager,

--------------------------------------------------------------------------------------------------------
batocera-emulationstation.mk ecb3e288a00f12c72a34fd9cf998d79a59894f46 # Version: Commits on May 23, 2024
--------------------------------------------------------------------------------------------------------
Merge pull request #1736 from Tartifless/master

Add gamecube and wii to cheevos systems,

------------------------------------------------------------------------------------------------
batocera-es-piboy.mk ecb3e288a00f12c72a34fd9cf998d79a59894f46 # Version: Commits on May 23, 2024
------------------------------------------------------------------------------------------------
Merge pull request #1736 from Tartifless/master

Add gamecube and wii to cheevos systems,