configs/aarch64_efi: Linux needs host-openssl to build
The Linux kernel builds fails with:

scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>

Because it needs host-openssl.

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/131216892

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>