libostree: add patch to fix compilation error
Fix the following compilation error:
src/libostree/ostree-repo-pull.c:1493:1: error: no previous prototype
for '_ostree_repo_verify_bindings' [-Werror=missing-prototypes]

The patch is submitted upstreams (8d3d14503b3105f93db635022e881e02688f2db4)
and should be removed in the next version bump.

Fixes:
http://autobuild.buildroot.net/results/3fc91565cb2d0fabe566c109257a616bd57cb08c

Signed-off-by: Marcus Folkesson <marcus.folkesson@gmail.com>
Tested-by: Matt Weber <matthew.weber@rockwellcollins.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>