Updates on Dec 01, 2025 19:45
-----------------------------------------------------------------------------------------------------
chromebook-linux-audio.mk 7910d56621b6af23946f4607bc008eb51dfc3e6e # Version: Commits on Dec 01, 2025
-----------------------------------------------------------------------------------------------------
hifi2/catpt: add driver selection of sst or sof,

--------------------------------------------------
faudio.mk 25.12 # Version: Commits on Dec 01, 2025
--------------------------------------------------
Fixes:

- An ungodly amount of cleanup for FACT:

    - Many magic numbers have been replaced with human-readable constants

    - Replace tons of asserts with proper error return codes

    - Initial work to revamp the notification subsystem

- CMake: Fix the pkg-config libdir and includedir

Thanks to our [GitHub Sponsors](https://github.com/sponsors/flibitijibibo/), including...

Super Duper Sponsors:

- [Re-Logic](https://re-logic.com/)

Super Sponsors:

- @CDGKen

- @compcj

- @jbevain

- @kg

- @NoelFB

- @superjoebob

- @terinfire

- @TerryCavanagh

Sponsors:

- @bartwe

- @bwiklund

- @Conan-Kudo

- @Eldirans

- @GlaireDaggers

- @isaboll1

- @isadorasophia

- @larsiusprime

- @tgpholly

- @xxxbxxx

- [Bit Kid Games](http://bitkidgames.com/)

- [Lunar Ray Games](http://www.lunarraygames.com/),

-----------------------------------------------------------------------------------
ares.mk dfb355495ac512c3d8451b004ed83884419957da # Version: Commits on Dec 01, 2025
-----------------------------------------------------------------------------------
pce: fix missing cd-da playback,

------------------------------------------------------------------------------------------
dolphin-emu.mk 213dc1c9afb4979dab357327387ab49ce17f174a # Version: Commits on Dec 01, 2025
------------------------------------------------------------------------------------------
Merge pull request #14178 from Dentomologist/jit64_avoid_passing_immediate_to_non_immediate_parameter

Jit64: Avoid passing immediate to non-immediate parameter,

-------------------------------------------------------------------
dosbox-x.mk dosbox-x-v2025.12.01 # Version: Commits on Dec 01, 2025
-------------------------------------------------------------------
2025.12.01

  - Video debug overlay: For Tandy and PCjr emulation, add information on

    the screen that shows the line mask, display and cpu memory banks and

    the corresponding segment values, which may aid in debugging issues

    with games and reveal any remapping or page flipping (joncampbell123).

  - Tandy emulation: Add the string \Tandy\ somewhere in the DOS kernel

    at startup if machine=tandy. The game \The Train: Escape to Normandy\

    scans from FFFF:0000 for the string \Tandy\ which of course wraps

    around to the first 64KB of memory where the DOS kernel resides. If

    it does not see this string, it does not think it is running on a Tandy.

    Such a detection routine will obviously break if you're on a 286 based

    Tandy with HMA enabled, or you're running normal MS-DOS on a Tandy

    system. This change allows the game to run (joncampbell123).

  - Tseng ET4000 emulation: Mode 0x24 is unusual in that it is a 130x28

    text mode with a 13-pixel high character cell. The ET4000 VGA BIOS

    apparently has a specific font for that mode, so, incorporate that

    font into DOSBox-X and use it for mode 0x24 (joncampbell123).

  - Tseng ET4000 emulation: Fix modes 0x22/0x23/0x24 to match how the

    actual VGA BIOS programs them. This fixes problems where the 132x25

    mode was rendered only on the upper half of the screen (joncampbell123).

  - Fix Tseng ET3000/ET4000 emulation bug where CGA graphics modes

    were garbled. The main VGA emulation no longer uses M_CGA2/M_CGA4

    and the ET4000 emulation needs to behave the same to fix the

    graphics modes. Apply fix to ET3000 emulation as well. (joncampbell123).

  - Some extra code in shell processing was preventing drive change commands

    if the last character was a backslash i.e. \a:\\\ instead of \a:\.

    Fixed. (joncampbell123).

  - INT 21h AH=4Bh EXEC: Real MS-DOS returns a nonzero value like 0x3E01.

    A buggy version of Magic Pockets fails to call INT 21 AH=4Dh to read

    the INTRO.EXE exit code and expects AL to just be nonzero to continue

    to the game. So to make it work properly (kind of), return a nonzero

    value. (joncampbell123).

  - Tandy machine type: Many registers are WRITE ONLY according to SX

    documentation, yet \Troubadours\ likes to read/modify/write those

    registers in what appears to be hand-rolled manual modesetting code

    to set up 320x200 16-color mode, so, add code to respond to reads

    from those ports with zeros and print a debug message to the log

    about how DOS games are not supposed to read those registers. Make

    the hand-rolled modesetting work by returning 0x00, rather than 0xFF.

    The code will not set up the mode correctly if 0xFF is returned, but

    will if 0x00 is returned. A side effect of this is that, since one

    of the registers controls the RAM address used as video memory, this

    moves it down to 512KB from base memory as well, which of course

    easily corrupts the very end of the MCB chain unless you enable more

    than 640KB of RAM and ask DOSBox-X to emulate the full Tandy 768KB

    of conventional memory. Though the game still crashes very easily,

    and in the exact same manner in both DOSBox-X and DOSBox SVN, this

    fix does solve the problem where the game was only able to draw

    2 out of 4 scanlines on the screen. (joncampbell123).

,

------------------------------------------------------------------------------------------
duckstation.mk af29ce010e6db711e6562e5ebc3fdb003c5d0719 # Version: Commits on Dec 01, 2025
------------------------------------------------------------------------------------------
Achievements: Show points for most recent unlock,

--------------------------------------------------------------------------------------
openmsx.mk 6174c91897abfd57fba3cfed319976650d62aaa6 # Version: Commits on Dec 01, 2025
--------------------------------------------------------------------------------------
ImGuiCharacter: implement override color table

See:

    Add an option to highlight patterns in tile viewer #2044

    https://github.com/openMSX/openMSX/issues/2044,

------------------------------------------------------------------------------------
rpcs3.mk 7e8ed5ecc102609fa0fc80d6a5ffe78d5c21e61e # Version: Commits on Nov 30, 2025
------------------------------------------------------------------------------------
rsx: clear unused parameters on capture boot,

-------------------------------------------------------------------------------------------
xenia-native.mk 016797d19c8a629081c80475723a1f3233e56c9b # Version: Commits on Dec 01, 2025
-------------------------------------------------------------------------------------------
[Emulator] Return error when device initialization fails

This should prevent \Install Content\ option to freeze in specific scenarios,

-----------------------------------------------------------------------------------------
lightspark.mk e6a761ad4f9a39d91af0d1993d0e7e3df9c45171 # Version: Commits on Dec 01, 2025
-----------------------------------------------------------------------------------------
mark install instructions as tested on Ubuntu 25.10,

------------------------------------------------------------------------------------
box64.mk 056999e8fd7ec7649762179f52e32819ef5e48e1 # Version: Commits on Dec 01, 2025
------------------------------------------------------------------------------------
Fixed exception handling on wine 10.19+,

------------------------------------------------------------------------------------
cdogs.mk 67ac3e4aa598fc6197bd770446dbbc0a7f6a8c02 # Version: Commits on Dec 01, 2025
------------------------------------------------------------------------------------
Noah cast #712,

---------------------------------------------------------------------------------------
corsixth.mk 726d56ff2f68f2c9c59469f748a7587700607e26 # Version: Commits on Nov 26, 2025
---------------------------------------------------------------------------------------
fixed bug in operating theatre that prevent patient to enter room,

------------------------------------------------------------------------------------------
devilutionx.mk b408ba1327d96ec00a80a5c69632ddb083e49139 # Version: Commits on Dec 01, 2025
------------------------------------------------------------------------------------------
Adjust translator comments,

---------------------------------------------------------------------------------------
etlegacy.mk 609312af770d11061a892c60be11dbad0b9f29a8 # Version: Commits on Dec 01, 2025
---------------------------------------------------------------------------------------
cgame: fix blood puff doesn't turn off properly

regression from 7289d4b,

---------------------------------------------------------------------------------------
stuntcar.mk 5f7300242e713c36aca10e372a6fc3de7bbb28dc # Version: Commits on Dec 01, 2025
---------------------------------------------------------------------------------------
Merge pull request #23 from akaunist-coder/win32-improvements

Win32 improvements,

----------------------------------------------------------------------------------------
supertux2.mk f605c4bf206042563cc75fd3e846ad958da4adb7 # Version: Commits on Dec 01, 2025
----------------------------------------------------------------------------------------
Extrapolate camera and Tux position in worldmap (#3419),

---------------------------------------------------------------------------------------
mangohud.mk 9553d85306a5a317a9571990c08bac10a8cac10a # Version: Commits on Dec 01, 2025
---------------------------------------------------------------------------------------
gpu_fdinfo: add missing implicit sstream header include

It's not implicit in gcc-16 anymore.

../src/gpu_fdinfo.cpp: In member function â€˜void GPU_fdinfo::get_current_hwmon_readings()â€™:

../src/gpu_fdinfo.cpp:287:27: error: aggregate â€˜std::stringstream ssâ€™ has incomplete type and cannot be defined

  287 |         std::stringstream ss;

      |

Signed-off-by: Alfred Wingate <parona@protonmail.com>,

-------------------------------------------------------------------------------------------------
shadps4-qtlauncher.mk 0d56f29269af7447f1030d99d3e24bb54f363019 # Version: Commits on Dec 01, 2025
-------------------------------------------------------------------------------------------------
Pre-release Folder Persistence (#208)

* Pre-release Folder Persistence

* -,

----------------------------------------------------------------------------------------
hid-tmff2.mk c4b70d4ec36404c9454199bec208eaf3116ef453 # Version: Commits on Dec 01, 2025
----------------------------------------------------------------------------------------
fix maybe uninitialized variable

+ Closes #183,

-----------------------------------------------------------------------------------------------
retroarch-assets.mk a7b711dfd74871e9985ba3b2fe2c15048a928aaf # Version: Commits on Dec 01, 2025
-----------------------------------------------------------------------------------------------
Merge pull request #492 from baxysquare/master

Icons for Systematic Theme,

--------------------------------------------------------------------------------------
vkquake.mk ec598f18bf6930e95872c251f930da165dd4e0de # Version: Commits on Dec 01, 2025
--------------------------------------------------------------------------------------
Better binary archives naming w.r.t Intel vs. Arm,

----------------------------------------------------------------------------------
trx.mk 9b916331f44d41b2b475652b5f4965f9a69d78ea # Version: Commits on Dec 01, 2025
----------------------------------------------------------------------------------
gun/control: prevent flare re-equip if already active

Resolves #4361.,

------------------------------------------------------------------------------------------
xash3d-fwgs.mk a4f8fc220570366a5d55822ef221f58097332ef8 # Version: Commits on Dec 01, 2025
------------------------------------------------------------------------------------------
engine: add clc_bad log packet cmd value,